
--[[
%% @module: 协议号关联表
%% @author: swordman sue
%% @created: 2016-07-26
--]]

Net = Net or {}

--界面打开前自动请求协议的对应关系表
Net.Protocol4OpenViewMap = Net.Protocol4OpenViewMap or 
{
	[Net.ProtocolNo.C2S_ARENA_DATA_REQ] = Net.ProtocolNo.S2C_ARENA_DATA_RESP,
	[Net.ProtocolNo.C2S_DAILY_MISSION_LIST_REQ] = Net.ProtocolNo.S2C_DAILY_MISSION_LIST_RESP,
	[Net.ProtocolNo.C2S_ACHIEVEMENT_LIST_REQ] = Net.ProtocolNo.S2C_ACHIEVEMENT_LIST_RESP,
	[Net.ProtocolNo.C2S_EMAIL_LIST_REQ] = Net.ProtocolNo.S2C_EMAIL_LIST_RESP,
	[Net.ProtocolNo.IPMENT_LIST_REQ] = Net.ProtocolNo.S2C_EQUIPMENT_LIST_RESP,
	[Net.ProtocolNo.C2S_FRIEND_LIST_REQ] = Net.ProtocolNo.S2C_FRIEND_LIST_RESP,
	[Net.ProtocolNo.C2S_FRIEND_APPLY_LIST_REQ] = Net.ProtocolNo.S2C_FRIEND_APPLY_LIST_RESP,
	[Net.ProtocolNo.C2S_HERO_RECRUITDATA_REQ] = Net.ProtocolNo.S2C_HERO_RECRUITDATA_RESP,
	[Net.ProtocolNo.C2S_HERO_COLLECTION_LIST_REQ] = Net.ProtocolNo.S2C_HERO_COLLECTION_LIST_RESP,
	[Net.ProtocolNo.C2S_PLUNDEREDTREASURES_DATA_REQ] = Net.ProtocolNo.S2C_PLUNDEREDTREASURES_DATA_RESP,
	[Net.ProtocolNo.C2S_RANK_LIST_REQ] = Net.ProtocolNo.S2C_RANK_LIST_RESP,
	[Net.ProtocolNo.C2S_REBEL_DATA_REQ] = Net.ProtocolNo.S2C_REBEL_DATA_RESP,
	[Net.ProtocolNo.C2S_SPIRIT_DATA_REQ] = Net.ProtocolNo.S2C_SPIRIT_DATA_RESP,
	[Net.ProtocolNo.C2S_HEART_OF_WORLD_DATA_REQ] = Net.ProtocolNo.S2C_HEART_OF_WORLD_DATA_RESP,
	
	--服务端红点数列表
	[Net.ProtocolNo.C2S_RED_POINT_LIST_REQ] = Net.ProtocolNo.S2C_RED_POINT_LIST_RESP,

	--每日签到
	[Net.ProtocolNo.C2S_SIGN_IN_DATA_REQ] = Net.ProtocolNo.S2C_SIGN_IN_DATA_RESP,
	--等级礼包
	[Net.ProtocolNo.C2S_LEVEL_GIFT_DATA_REQ] = Net.ProtocolNo.S2C_LEVEL_GIFT_DATA_RESP,
	--VIP礼包
	[Net.ProtocolNo.C2S_VIP_GIFT_DATA_REQ] = Net.ProtocolNo.S2C_VIP_GIFT_DATA_RESP,
	--摇钱树
	[Net.ProtocolNo.C2S_YCS_DATA_REQ] = Net.ProtocolNo.S2C_YCS_DATA_RESP,
}

--需要loading的协议的对应关系表
Net.ProtocolLoadingMap = Net.ProtocolLoadingMap or 
{
	[Net.ProtocolNo.MSG_C2S_FB_MAIN_DATA_REQ] = Net.ProtocolNo.MSG_S2C_FB_MAIN_DATA_RESP,
	[Net.ProtocolNo.C2S_FB_DAILY_DATA_REQ] = Net.ProtocolNo.S2C_FB_DAILY_DATA_RESP,
	[Net.ProtocolNo.C2S_FB_HERO_DATA_REQ] = Net.ProtocolNo.S2C_FB_HERO_DATA_RESP,

	[Net.ProtocolNo.IPMENT_LIST_REQ] = Net.ProtocolNo.S2C_EQUIPMENT_LIST_RESP,
	[Net.ProtocolNo.C2S_RANK_LIST_REQ] = Net.ProtocolNo.S2C_RANK_LIST_RESP,
	[Net.ProtocolNo.C2S_EMAIL_LIST_REQ] = Net.ProtocolNo.S2C_EMAIL_LIST_RESP,
	[Net.ProtocolNo.C2S_REBEL_DATA_REQ] = Net.ProtocolNo.S2C_REBEL_DATA_RESP,
	[Net.ProtocolNo.C2S_HERO_RECRUITDATA_REQ] = Net.ProtocolNo.S2C_HERO_RECRUITDATA_RESP,
	[Net.ProtocolNo.C2S_HERO_COLLECTION_LIST_REQ] = Net.ProtocolNo.S2C_HERO_COLLECTION_LIST_RESP,
	[Net.ProtocolNo.C2S_HEART_OF_WORLD_DATA_REQ] = Net.ProtocolNo.S2C_HEART_OF_WORLD_DATA_RESP,
	[Net.ProtocolNo.C2S_PLUNDEREDTREASURES_DATA_REQ] = Net.ProtocolNo.S2C_PLUNDEREDTREASURES_DATA_RESP,
	[Net.ProtocolNo.C2S_ARENA_DATA_REQ] = Net.ProtocolNo.S2C_ARENA_DATA_RESP,
	[Net.ProtocolNo.C2S_DAILY_MISSION_LIST_REQ] = Net.ProtocolNo.S2C_DAILY_MISSION_LIST_RESP,
	[Net.ProtocolNo.C2S_ACHIEVEMENT_LIST_REQ] = Net.ProtocolNo.S2C_ACHIEVEMENT_LIST_RESP,
	[Net.ProtocolNo.C2S_FRIEND_APPLY_LIST_REQ] = Net.ProtocolNo.S2C_FRIEND_APPLY_LIST_RESP,
	[Net.ProtocolNo.C2S_FRIEND_LIST_REQ] = Net.ProtocolNo.S2C_FRIEND_LIST_RESP,

	[Net.ProtocolNo.C2S_LOGIN_ACCOUNT_REQ] = Net.ProtocolNo.S2C_LOGIN_ACCOUNT_RESP,
	[Net.ProtocolNo.C2S_LOGIN_SELECT_SERVER_REQ] = Net.ProtocolNo.S2C_LOGIN_SELECT_SERVER_RESP,
	[Net.ProtocolNo.C2S_LOGIN_CREATE_ROLE_REQ] = Net.ProtocolNo.S2C_LOGIN_CREATE_ROLE_RESP,
	[Net.ProtocolNo.C2S_START_GAME_REQ] = Net.ProtocolNo.S2C_START_GAME_RESP,
	[Net.ProtocolNo.C2S_BATTLE_START_REQ] = Net.ProtocolNo.S2C_BATTLE_START_RESP,
	[Net.ProtocolNo.C2S_BATTLE_END_REQ] = Net.ProtocolNo.S2C_BATTLE_END_RESP,	
	[Net.ProtocolNo.C2S_SERVER_TIME_REQ] = Net.ProtocolNo.S2C_SERVER_TIME_RESP,	
	[Net.ProtocolNo.MSG_C2S_SHOP_GOODS_BUY_RECORD_REQ] = Net.ProtocolNo.MSG_S2C_SHOP_GOODS_BUY_RECORD_RESP,	
	[Net.ProtocolNo.C2S_PLUNDEREDTREASURES_FIVETIMES_REQ] = Net.ProtocolNo.S2C_PLUNDEREDTREASURES_FIVETIMES_RESP,
	[Net.ProtocolNo.C2S_FRIEND_ENERGY_GIVE_REQ] = Net.ProtocolNo.S2C_FRIEND_ENERGY_GIVE_RESP,
	[Net.ProtocolNo.C2S_FRIEND_ENERGY_GET_REQ] = Net.ProtocolNo.S2C_FRIEND_ENERGY_GET_RESP,
	[Net.ProtocolNo.C2S_ACHIEVEMENT_AWARD_REQ] = Net.ProtocolNo.S2C_ACHIEVEMENT_AWARD_RESP,
	[Net.ProtocolNo.C2S_BATTLE_ASSIST_TARGET_REQ] = Net.ProtocolNo.S2C_BATTLE_ASSIST_TARGET_RESP,
	[Net.ProtocolNo.C2S_SPIRIT_ENHANCE_REQ] = Net.ProtocolNo.S2C_SPIRIT_ENHANCE_RESP,
	[Net.ProtocolNo.C2S_SPIRIT_USE_REQ] = Net.ProtocolNo.S2C_SPIRIT_USE_RESP,
	[Net.ProtocolNo.C2S_SPIRIT_DATA_REQ] = Net.ProtocolNo.S2C_SPIRIT_DATA_RESP,
	[Net.ProtocolNo.C2S_HERO_AWAKEN_REQ] = Net.ProtocolNo.S2C_HERO_AWAKEN_RESP,
	[Net.ProtocolNo.C2S_TREASURE_BOX_LOCK_REQ] = Net.ProtocolNo.S2C_TREASURE_BOX_LOCK_RESP,
	[Net.ProtocolNo.C2S_ATTACK_CITY_ENCOURAGE_REQ] = Net.ProtocolNo.S2C_ATTACK_CITY_ENCOURAGE_RESP,
	[Net.ProtocolNo.C2S_SPRITE_TRAIN_REQ] = Net.ProtocolNo.S2C_SPRITE_TRAIN_RESP,
	[Net.ProtocolNo.C2S_HERO_BREACH_REQ] = Net.ProtocolNo.S2C_HERO_BREACH_RESP,
	[Net.ProtocolNo.C2S_HERO_UPGRADE_REQ] = Net.ProtocolNo.S2C_HERO_UPGRADE_RESP,
	[Net.ProtocolNo.C2S_HERO_RECRUIT_REQ] = Net.ProtocolNo.S2C_HERO_RECRUIT_RESP,
	[Net.ProtocolNo.C2S_HEART_OF_WORLD_LEVEL_UP_REQ] = Net.ProtocolNo.S2C_HEART_OF_WORLD_LEVEL_UP_RESP,
	[Net.ProtocolNo.C2S_FB_ONE_KEY_TAKE_REWARD_REQ] = Net.ProtocolNo.S2C_FB_ONE_KEY_TAKE_REWARD_RESP,
	[Net.ProtocolNo.C2S_MAP_COMMENT_LIST_REQ] = Net.ProtocolNo.S2C_MAP_COMMENT_LIST_RESP,
	[Net.ProtocolNo.C2S_PLUNDEREDTREASURES_TARGET_LIST_REQ] = Net.ProtocolNo.S2C_PLUNDEREDTREASURES_TARGET_LIST_RESP,
	[Net.ProtocolNo.C2S_TAKE_ACCURATE_RECOMMEND_GIFT_REQ] = Net.ProtocolNo.S2C_TAKE_ACCURATE_RECOMMEND_GIFT_RESP,
	[Net.ProtocolNo.C2S_HERO_TRAIN_REQ] = Net.ProtocolNo.S2C_HERO_TRAIN_RESP,
	[Net.ProtocolNo.C2S_LOGIN_CHANGE_ROLE_NAME_REQ] = Net.ProtocolNo.S2C_LOGIN_CHANGE_ROLE_NAME_RESP,
	[Net.ProtocolNo.C2S_HERO_TRAIN_REPLACE_REQ] = Net.ProtocolNo.S2C_HERO_TRAIN_REPLACE_RESP,
	[Net.ProtocolNo.C2S_CHOOSE_CARD_REQ] = Net.ProtocolNo.S2C_CHOOSE_CARD_RESP,
	[Net.ProtocolNo.C2S_FRIEND_APPLY_REPLY_REQ] = Net.ProtocolNo.S2C_FRIEND_APPLY_REPLY_RESP,
	[Net.ProtocolNo.C2S_DAILY_MISSION_AWARD_REQ] = Net.ProtocolNo.S2C_DAILY_MISSION_AWARD_RESP,
	[Net.ProtocolNo.C2S_SPRITE_BLESS_REQ] = Net.ProtocolNo.S2C_SPRITE_BLESS_RESP,
	[Net.ProtocolNo.C2S_TAKE_FACEBOOK_COMMEND_REWARD_REQ] = Net.ProtocolNo.S2C_TAKE_FACEBOOK_COMMEND_REWARD_RESP,
	
	[Net.ProtocolNo.C2S_HERO_GOTO_BATTLE_REQ] = Net.ProtocolNo.S2C_HERO_GOTO_BATTLE_RESP,

	[Net.ProtocolNo.C2S_EQUIPMENT_ONE_KEY_ENHANCE_REQ] = Net.ProtocolNo.S2C_EQUIPMENT_ONE_KEY_ENHANCE_RESP,

	[Net.ProtocolNo.C2S_PVP_READY_FINISH_REQ] = Net.ProtocolNo.S2C_PVP_READY_FINISH_RESP,

	[Net.ProtocolNo.C2S_FB_AWARD_GET_REQ] = Net.ProtocolNo.S2C_FB_AWARD_GET_RESP,

	[Net.ProtocolNo.C2S_SDK_LOGIN_REQ] = Net.ProtocolNo.S2C_SDK_LOGIN_RESP,

	[Net.ProtocolNo.C2S_SDK_ORDER_ID_REQ] = Net.ProtocolNo.S2C_SDK_ORDER_ID_RESP,

	[Net.ProtocolNo.C2S_ITEM_USE_REQ] = Net.ProtocolNo.S2C_ITEM_USE_RESP,	

	[Net.ProtocolNo.C2S_SCENE_ENTER_REQ] = Net.ProtocolNo.S2C_SCENE_ENTER_RESP,

	[Net.ProtocolNo.C2S_SCENE_LEAVE_REQ] = Net.ProtocolNo.S2C_SCENE_LEAVE_RESP,

	--商店购买转圈 防止重复购买
	[Net.ProtocolNo.MSG_C2S_SHOP_GOODS_BUY_REQ] = Net.ProtocolNo.MSG_S2C_SHOP_GOODS_BUY_RESP,

	[Net.ProtocolNo.C2S_SEVEN_DAY_GET_REWARD_REQ] = Net.ProtocolNo.S2C_SEVEN_DAY_GET_REWARD_RESP,

	--组队
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_ANSWER_QUESTION_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_ANSWER_QUESTION_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_NEXT_NPC_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_NEXT_NPC_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_LOTTERY_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_LOTTERY_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_LEAVE_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_LEAVE_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_DATA_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_DATA_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_CREATE_TEAM_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_CREATE_TEAM_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_ACCEPT_INVITE_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_ACCEPT_INVITE_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_MATCH_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_MATCH_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_CANCEL_MATCH_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_CANCEL_MATCH_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_ACCEPT_TASK_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_ACCEPT_TASK_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_TASK_START_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_TASK_START_RESP,
	[Net.ProtocolNo.C2S_TEAM_DUNGEON_BOSS_TASK_START_REQ] = Net.ProtocolNo.S2C_TEAM_DUNGEON_BOSS_TASK_START_RESP,

	--圣诞活动
	[Net.ProtocolNo.C2S_CHRISTMAS_DATA_REQ] = Net.ProtocolNo.S2C_CHRISTMAS_DATA_RESP,
	[Net.ProtocolNo.C2S_CHRISTMAS_BATTLE_ENTER_REQ] = Net.ProtocolNo.S2C_CHRISTMAS_BATTLE_ENTER_RESP,
	[Net.ProtocolNo.C2S_CHRISTMAS_ATTACK_BOSS_REQ] = Net.ProtocolNo.S2C_CHRISTMAS_ATTACK_BOSS_RESP,
	[Net.ProtocolNo.C2S_CHRISTMAS_TAKE_BOSS_REWARD_REQ] = Net.ProtocolNo.S2C_CHRISTMAS_TAKE_BOSS_REWARD_RESP,

	--属性
	[Net.ProtocolNo.C2S_TOWER_SELECT_PRO_REQ] = Net.ProtocolNo.S2C_TOWER_SELECT_PRO_RESP,
	--扫荡
	[Net.ProtocolNo.C2S_TOWER_ONE_KEY_CLEAN_REQ] = Net.ProtocolNo.S2C_TOWER_ONE_KEY_CLEAN_RESP,

	--积分赛
	[Net.ProtocolNo.C2S_SCORE_MATCH_REFRESH_TARGET_REQ] = Net.ProtocolNo.S2C_SCORE_MATCH_REFRESH_TARGET_RESP,

}
