#pragma once
#include "header.pb.h"

class GateServerSession;
class protocol::Header;

//GateSvr消息处理器
class HandlerFromGate
{
public:
	HandlerFromGate(void);
	~HandlerFromGate(void);
	#define DEFINE_MSG_PROC(X) static VOID OnMSG_##X(GateServerSession * pSession, NetMsgBody *pMsg, DWORD dwGuid);

/*--------------------------------------------------------------------------------------------------------------------------*/
	//来自Client
	////////////////////////////////////////定义函数//////////////////////////////////////////////////

	// 系统级别消息
// 	DEFINE_MSG_PROC(Msg_Heart_Beat_G2M);				// 心跳(网关与逻辑服)
// 	DEFINE_MSG_PROC(Msg_Client_Disconnet_G2M)			// 断开连接

	// 登录,角色
	DEFINE_MSG_PROC(C2S_LOGIN_ACCOUNT_REQ);				// 帐号登录(普通)
	DEFINE_MSG_PROC(C2S_LOGIN_SELECT_SERVER_REQ);		// 选择服务器
	DEFINE_MSG_PROC(C2S_LOGIN_CREATE_ROLE_REQ);			// 创建角色
	DEFINE_MSG_PROC(C2S_ROLE_DETAILS_REQ);
	DEFINE_MSG_PROC(C2S_ROLE_PRO_RECOVER_REQ);
	DEFINE_MSG_PROC(C2S_HEAD_IMAGE_REPLACE_REQ);
	DEFINE_MSG_PROC(C2S_ROLE_NAME_MODIFY_REQ);
	DEFINE_MSG_PROC(C2S_START_GAME_REQ);
	DEFINE_MSG_PROC(C2S_ACCOUNT_REGISTER_REQ);
	DEFINE_MSG_PROC(C2S_ACCOUNT_PASSWORD_CHANGE_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_ACTIVITY_GIFT_REQ);
	DEFINE_MSG_PROC(C2S_ACTIVITY_NOTICE_REQ);
	DEFINE_MSG_PROC(C2S_AUTHENTICATION_CODE_REQ);
	DEFINE_MSG_PROC(C2S_MOBILE_BIND_REQ);
	DEFINE_MSG_PROC(C2S_SDK_LOGIN_REQ);					// 帐号登录(sdk)
	DEFINE_MSG_PROC(C2S_SDK_ORDER_ID_REQ);
	DEFINE_MSG_PROC(C2S_RECHARGE_SUCCESS_REPORT_REQ);
	DEFINE_MSG_PROC(C2S_HERO_GOTO_REQ);
	DEFINE_MSG_PROC(C2S_ENTER_SCENE_REQ);
	DEFINE_MSG_PROC(C2S_LEAVE_SCENE_REQ);
	DEFINE_MSG_PROC(C2S_SCENE_ITEM_LOCK_REQ);
	DEFINE_MSG_PROC(C2S_SCENE_ITEM_PICK_UP_REQ);
	DEFINE_MSG_PROC(C2S_LOGIN_REQ);
	DEFINE_MSG_PROC(C2S_NEW_ROLE_GUIDE_UPDATE_REQ);

	// 战斗
	DEFINE_MSG_PROC(C2S_BATTLE_START_REQ);	// 战斗开始
	DEFINE_MSG_PROC(C2S_BATTLE_END_REQ);	// 战斗结束
	DEFINE_MSG_PROC(C2S_HELP_BATTLE_TARGET_REQ);

	// 排行榜
	DEFINE_MSG_PROC(C2S_RANK_LIST_REQ);
	DEFINE_MSG_PROC(C2S_RANK_LIKE_REQ);
	DEFINE_MSG_PROC(C2S_RANK_LEAVE_MESSAGE_REQ);
	DEFINE_MSG_PROC(C2S_RANK_LEAVE_MESSAGE_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_RANK_LIST_REQ);
	DEFINE_MSG_PROC(C2S_MY_RANK_REQ);


	// 聊天
	DEFINE_MSG_PROC(C2S_CHAT_REQ);			// 聊天请求
	DEFINE_MSG_PROC(C2S_CHAT_VOICE_REQ);	// 语音请求
	DEFINE_MSG_PROC(C2S_CHAT_RECORD_LIST_REQ);

	DEFINE_MSG_PROC(C2M_GM_REQ);

	// 商店
	DEFINE_MSG_PROC(C2S_SHOP_GOODS_BUY_REQ);
	DEFINE_MSG_PROC(C2S_SHOP_GOODS_BUY_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_SHOP_GOODS_SELL_REQ);
	DEFINE_MSG_PROC(C2S_SHOP_LIMIT_GOODS_LIST_REQ);
	DEFINE_MSG_PROC(C2S_SHOP_REFRESH_REQ);
	DEFINE_MSG_PROC(C2S_HERO_SHOP_DATA_REQ);
	DEFINE_MSG_PROC(C2S_AWAKEN_SHOP_DATA_REQ);
	DEFINE_MSG_PROC(C2S_STAR_SOUL_SHOP_DATA_REQ);
	DEFINE_MSG_PROC(C2S_DIRECT_SHOP_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_DIRECT_BUY_GOODS_REQ);
	DEFINE_MSG_PROC(C2S_CRYSTAL_SHOP_DATA_REQ);


	// 副本
	DEFINE_MSG_PROC(C2S_FB_MAIN_DATA_REQ);
	DEFINE_MSG_PROC(C2S_FB_AWARD_GET_REQ);
	DEFINE_MSG_PROC(C2S_TOWER_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TOWER_BUY_TIMES_REQ);
	DEFINE_MSG_PROC(C2S_TOWER_RESET_REQ);
	DEFINE_MSG_PROC(C2S_TOWER_SELECT_PRO_REQ);
	DEFINE_MSG_PROC(C2S_TOWER_BUY_STAR_GOODS_REQ);
	DEFINE_MSG_PROC(C2S_FB_DAILY_DATA_REQ);
	DEFINE_MSG_PROC(C2S_FB_HERO_DATA_REQ);
	DEFINE_MSG_PROC(C2S_FB_CLEAN_REQ);
	DEFINE_MSG_PROC(C2S_FB_ELITE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TOWER_ONE_KEY_CLEAN_REQ);
	DEFINE_MSG_PROC(C2S_FB_RESET_REQ);
	DEFINE_MSG_PROC(C2S_FB_ONE_KEY_TAKE_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_MAIN_FB_CHAPTER_REWARD_REQ);

	// 领地
	DEFINE_MSG_PROC(C2S_PLAYER_LAND_DATA_REQ);
	DEFINE_MSG_PROC(C2S_LAND_PATROL_REQ);
	DEFINE_MSG_PROC(C2S_LAND_VIEW_PATROL_AWARD_REQ);
	DEFINE_MSG_PROC(C2S_LAND_GET_PATROL_AWARD_REQ);
	DEFINE_MSG_PROC(C2S_LAND_SKILL_LEVELUP_REQ);
	DEFINE_MSG_PROC(C2S_LAND_SUPPRESS_RIOT_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_LAND_LIST_REQ);
	DEFINE_MSG_PROC(C2S_LAND_CITY_DETAILS_REQ);

	// 精灵
	DEFINE_MSG_PROC(C2S_SPIRIT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_HEART_OF_WORLD_LEVEL_UP_REQ);
	DEFINE_MSG_PROC(C2S_SPIRIT_ENHANCE_REQ);
	DEFINE_MSG_PROC(C2S_SPIRIT_USE_REQ);
	DEFINE_MSG_PROC(C2S_HEART_OF_WORLD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_SPIRIT_TRAIN_REQ);
	DEFINE_MSG_PROC(C2S_SPRITE_STAR_UP_REQ);
	DEFINE_MSG_PROC(C2S_SPRITE_BLESS_REQ);
	DEFINE_MSG_PROC(C2S_SPRITE_COMPOSE_REQ);


	// 工会
	DEFINE_MSG_PROC(C2S_GUILD_DATE_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_CREATE_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_DISMISS_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_APPLY_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_APPLY_CHECK_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_APPLY_CANCEL_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_KICKOUT_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_LEAVE_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_APPOINT_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_LEAVE_MESSAGE_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_SEARCH_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_QY_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_QS_AWARD_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_APPLY_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_LEAVEMSG_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_MEMBER_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_INFO_MODIFY_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_EVENT_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_SKILL_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_SKILL_LEVEL_UP_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_DATA_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_CHAPTER_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_MAP_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_MAP_REWARD_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_DAMAGE_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_BATTLE_TIMES_BUY_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_IMPEACH_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_MONSTER_DATA_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_FB_CHAPTER_RESET_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_MY_MAP_REWARD_RECORD_REQ);

	// 成就
	DEFINE_MSG_PROC(C2S_ACHIEVEMENT_LIST_REQ);
	DEFINE_MSG_PROC(C2S_ACHIEVEMENT_AWARD_REQ);

	// 日常任务
	DEFINE_MSG_PROC(C2S_DAILY_MISSION_LIST_REQ);
	DEFINE_MSG_PROC(C2S_DAILY_MISSION_AWARD_REQ);
	DEFINE_MSG_PROC(C2S_DAILY_MISSION_POINT_AWARD_REQ);

	// 世界BOSS
	DEFINE_MSG_PROC(C2S_WORLD_BOSS_DATA_REQ);
	DEFINE_MSG_PROC(C2S_WORLD_BOSS_SELECT_CAMP_REQ);
	DEFINE_MSG_PROC(C2S_WORLD_BOSS_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_WORLD_BOSS_REWARD_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_WORLD_BOSS_BATTLE_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_WORLD_BOSS_BATTLE_TIMES_BUY_REQ);

	// 竞技场
	DEFINE_MSG_PROC(C2S_ARENA_TARGET_LIST_REQ);
	DEFINE_MSG_PROC(C2S_ARENA_BATTLE_RECORD_REQ);

	// 物品
	DEFINE_MSG_PROC(C2S_ITEM_LIST_REQ);
	DEFINE_MSG_PROC(C2S_ITEM_USE_REQ);
	DEFINE_MSG_PROC(C2S_ITEM_FP_REQ);
	DEFINE_MSG_PROC(C2S_ITEM_COMPOSE_REQ);
	DEFINE_MSG_PROC(C2S_ITEM_DECOMPOSE_REQ);

	// 邮件
	DEFINE_MSG_PROC(C2S_EMAIL_LIST_REQ);

	// 装备
	DEFINE_MSG_PROC(C2S_EQUIPMENT_LIST_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_COMPOSE_REQ);
	//DEFINE_MSG_PROC(C2S_EQUIPMENT_FRAGMENT_LIST_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_STRENG_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_REFINE_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_PUT_ON_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_ONE_KEY_ENHANCE_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_STAR_UP_REQ);
	DEFINE_MSG_PROC(C2S_EQUIPMENT_QUALITY_UP_REQ);

	// 宝物
	DEFINE_MSG_PROC(C2S_TREASURE_LIST_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_STRENGTHEN_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_REFINE_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_COMPOSE_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_PUT_ON_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_SMELT_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_QUALITY_UP_REQ);

	// 叛军
	DEFINE_MSG_PROC(C2S_REBEL_DATA_REQ);
	DEFINE_MSG_PROC(C2S_REBEL_EXPLOIT_AWARD_REQ);
	DEFINE_MSG_PROC(C2S_REBEL_EXPLOIT_AWARD_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_REBEL_SHARE_REQ);

	// 回收
	DEFINE_MSG_PROC(C2S_RECYCLE_DECOMPOSE_REQ);
	DEFINE_MSG_PROC(C2S_RECYCLE_RESET_REQ);
	DEFINE_MSG_PROC(C2S_RECYCLE_DECOMPOSE_RETURN_REQ);
	DEFINE_MSG_PROC(C2S_RECYCLE_RESET_RETURN_REQ);

	// 夺宝
	DEFINE_MSG_PROC(C2S_DUOBAO_DATA_REQ);
	DEFINE_MSG_PROC(C2S_DUOBAO_TARGET_LIST_REQ);
	DEFINE_MSG_PROC(C2S_DUOBAO_FIVE_TIMES_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_DUOBAO_PROGRESS_REWARD_REQ);


	// 英雄
	DEFINE_MSG_PROC(C2S_HERO_BASE_LIST_REQ);
	DEFINE_MSG_PROC(C2S_HERO_INFO_REQ);
	//DEFINE_MSG_PROC(C2S_FRAGMENT_LIST_REQ);
	DEFINE_MSG_PROC(C2S_HERO_TO_BATTLE_REQ);
	DEFINE_MSG_PROC(C2S_HERO_COLLECTION_LIST_REQ);
	DEFINE_MSG_PROC(C2S_HERO_COMPOSE_REQ);
	DEFINE_MSG_PROC(C2S_HERO_LEVEL_UP_REQ);
	DEFINE_MSG_PROC(C2S_HERO_BREAK_REQ);
	DEFINE_MSG_PROC(C2S_HERO_TRAIN_REQ);
	DEFINE_MSG_PROC(C2S_HERO_SUMMON_REQ);
	DEFINE_MSG_PROC(C2S_HERO_DESTINY_REQ);
	DEFINE_MSG_PROC(C2S_HERO_SELL_REQ);
	DEFINE_MSG_PROC(C2S_REINFORCEMENT_TO_BATTLE_REQ);
	DEFINE_MSG_PROC(C2S_HERO_SUMMON_DATA_REQ);
	DEFINE_MSG_PROC(C2S_HERO_AWAKEN_REQ);
	DEFINE_MSG_PROC(C2S_HERO_EQUIP_AWAKEN_ITEM_REQ);
	DEFINE_MSG_PROC(C2S_HERO_TRAIN_REPLACE_REQ);
	DEFINE_MSG_PROC(C2S_HERO_TRAIN_REWARD_GET_REQ);
	DEFINE_MSG_PROC(C2S_HERO_EVOLUTION_REQ);
	DEFINE_MSG_PROC(C2S_HERO_VIP_SUMMON_REQ);

	// 好友
	DEFINE_MSG_PROC(C2S_FRIEND_LIST_REQ);
	DEFINE_MSG_PROC(C2S_BLACK_LIST_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_APPLY_LIST_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_RECOMMEND_LIST_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_ADD_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_DEL_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_APPLY_REPLY_REQ);
	DEFINE_MSG_PROC(C2S_BLACK_ADD_REQ);
	DEFINE_MSG_PROC(C2S_BLACK_DEL_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_ENERGY_GIVE_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_ENERGY_GET_REQ);
	DEFINE_MSG_PROC(C2S_FRIEND_TARGET_FIND_REQ);

	// 奖励中心
	DEFINE_MSG_PROC(C2S_REWARD_CENTER_LIST_REQ);
	DEFINE_MSG_PROC(C2S_REWARD_CENTER_GET_REQ);

	// 签到
	DEFINE_MSG_PROC(C2S_SIGN_IN_DATA_REQ);
	DEFINE_MSG_PROC(C2S_SIGN_IN_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_LUXURY_SIGN_IN_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_LUXURY_SIGN_IN_DATA_REQ);

	// 迎财神
	DEFINE_MSG_PROC(C2S_YCS_DATA_REQ);
	DEFINE_MSG_PROC(C2S_YCS_REWARD_REQ);

	// 铜雀台
	DEFINE_MSG_PROC(C2S_TQT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TQT_REWARD_REQ);

	// 7天
	DEFINE_MSG_PROC(C2S_SEVEN_DAY_TARGET_LIST_REQ);
	DEFINE_MSG_PROC(C2S_SEVEN_DAY_GET_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_SEVEN_DAY_COMPLETION_REWARD_REQ);

	// 仙灵
	DEFINE_MSG_PROC(C2S_PLAYER_ZHANBU_DATA_REQ);
	DEFINE_MSG_PROC(C2S_CARD_LIST_REQ);
	DEFINE_MSG_PROC(C2S_FAIRY_POKEDEX_LIST_REQ);
	DEFINE_MSG_PROC(C2S_CARD_LEVEL_UP_REQ);
	DEFINE_MSG_PROC(C2S_CARD_BREAK_REQ);
	DEFINE_MSG_PROC(C2S_FAIRY_RECRUIT_REQ);
	DEFINE_MSG_PROC(C2S_FAIRY_POKEDEX_STAR_UP_REQ);
	DEFINE_MSG_PROC(C2S_FAIRY_POKEDEX_REVIVE_REQ);
	DEFINE_MSG_PROC(C2S_FAIRY_MAP_REFRESH_REQ);
	DEFINE_MSG_PROC(C2S_FAIRY_ACHIEVEMENT_ACTIVATION_REQ);
	DEFINE_MSG_PROC(C2S_CARD_REFRESH_REQ);
	DEFINE_MSG_PROC(C2S_OPEN_CARD_REQ);
	DEFINE_MSG_PROC(C2S_LOW_CARD_GROUP_REFRESH_TIMES_UPDATE_REQ);
	DEFINE_MSG_PROC(C2S_CELLECTION_GROUP_ACTIVATE_REQ);
	DEFINE_MSG_PROC(C2S_CELLECTION_GROUP_STAR_UP_REQ);
	DEFINE_MSG_PROC(C2S_COLLECTION_BOOK_LIST_REQ);
	DEFINE_MSG_PROC(C2S_CELLECTION_GROUP_RESET_REQ);
	DEFINE_MSG_PROC(C2S_COLLECTION_EQUIP_CARD_REQ);
	DEFINE_MSG_PROC(C2S_COLLECTION_UNLOAD_CARD_REQ);
	DEFINE_MSG_PROC(C2S_ZHAN_BU_ACHIEVEMENT_ACIVATE_REQ);


	// 积分赛
	DEFINE_MSG_PROC(C2S_SCORE_MATCH_DATA_REQ);
	DEFINE_MSG_PROC(C2S_SCORE_MATCH_SELECT_CAMP_REQ);
	DEFINE_MSG_PROC(C2S_SCORE_MATCH_REFRESH_TARGET_REQ);
	DEFINE_MSG_PROC(C2S_SCORE_MATCH_BUY_BATTLE_TIMES_REQ);
	DEFINE_MSG_PROC(C2S_SCORE_MATCH_TAKE_TASK_REWARD_REQ);

	// 争霸赛
	DEFINE_MSG_PROC(C2S_WARCRAFT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_WARCRAFT_BUY_BATTLE_TIMES_REQ);
	DEFINE_MSG_PROC(C2S_WARCRAFT_TARGET_LIST_REQ);
	DEFINE_MSG_PROC(C2S_WARCRAFT_RANK_LIST_REQ);
	DEFINE_MSG_PROC(C2S_WARCRAFT_CHEER_REQ);

	// 称号
	DEFINE_MSG_PROC(C2S_ROLE_TITLE_INFO_REQ);
	DEFINE_MSG_PROC(C2S_USE_TITLE_REQ);

	// 红点
	DEFINE_MSG_PROC(C2S_RED_POINT_LIST_REQ);

	// VIP礼包
	DEFINE_MSG_PROC(C2S_VIP_GIFT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_VIP_DAILY_GIFT_GET_REQ);
	DEFINE_MSG_PROC(C2S_VIP_WEEK_GIFT_BUY_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_TODAY_RECOMMEND_REWARD_REQ);

	// 等级礼包
	DEFINE_MSG_PROC(C2S_LEVEL_SHOP_ACTIVITY_DATA_REQ);

	// 开服基金
	DEFINE_MSG_PROC(C2S_OPEN_SERVER_FUND_DATA_REQ);
	DEFINE_MSG_PROC(C2S_OPEN_SERVER_FUND_BUY_REQ);
	DEFINE_MSG_PROC(C2S_OPEN_SERVER_FUND_REWARD_TAKE_REQ);
	DEFINE_MSG_PROC(C2S_ALL_PEOPLE_WELFARE_TAKE_REQ);

	// 限时优惠
	DEFINE_MSG_PROC(C2S_LIMIT_PREFERENTIAL_DATA_REQ);
	DEFINE_MSG_PROC(C2S_LIMIT_PREFERENTIAL_WELFARE_TAKE_REQ);

	// 等级礼包
	DEFINE_MSG_PROC(C2S_LEVEL_GIFT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_LEVEL_GIFT_REWARD_REQ);

	// 次日奖励
	DEFINE_MSG_PROC(C2S_NEXT_DAY_REWARD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_NEXT_DAY_REWARD_TAKE_REQ);

	// 玩家留言
	DEFINE_MSG_PROC(C2S_PLAYER_LEVEL_MESSAGE_REQ);

	// 关卡评论
	DEFINE_MSG_PROC(C2S_MAP_COMMENT_LIST_REQ);
	DEFINE_MSG_PROC(C2S_MAP_COMMENT_REQ);
	DEFINE_MSG_PROC(C2S_MAP_COMMENT_LIKE_REQ);

	// 充值
	DEFINE_MSG_PROC(C2S_RECHARGE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_RECHARGE_REQ);
	DEFINE_MSG_PROC(C2S_MONTH_CARD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_MONTH_CARD_BUY_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_MONTH_CARD_REWARD_REQ);

	// PVP
	DEFINE_MSG_PROC(C2S_PVP_SEARCH_TARGET_REQ);
	//DEFINE_MSG_PROC(C2S_PVP_STOP_SEARCH_TARGET_REQ);
	DEFINE_MSG_PROC(C2S_PVP_READY_FINISH_REQ);
	DEFINE_MSG_PROC(C2S_PVP_USE_SKILL_REQ);
	DEFINE_MSG_PROC(C2S_PVP_CREATE_BUFF_REQ);
	DEFINE_MSG_PROC(C2S_PVP_HP_CHANGE_REQ);
	DEFINE_MSG_PROC(C2S_PVP_BATTLE_RESULT_REQ);
	DEFINE_MSG_PROC(C2S_PVP_TAKE_BATTLE_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_PLAYER_PVP_DATA_REQ);
	DEFINE_MSG_PROC(C2S_PVP_SELECT_SPRIT_SKILL_REQ);
	DEFINE_MSG_PROC(C2S_PVP_CANCEL_SEARCH_TARGET_REQ);

	// 限时活动
	DEFINE_MSG_PROC(C2S_LIMIT_FIRST_RECHARGE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_LIMIT_SINGLE_RECHARGE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_LIMIT_ACCUMULATE_RECHARGE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_LIMIT_RECRUIT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_LIMIT_ACTIVITY_REWARD_REQ);

	// 攻城
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_DATA_REQ);
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_ENTER_REQ);
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_LEAVE_REQ);
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_GOTO_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_BOX_LOCK_REQ);
	DEFINE_MSG_PROC(C2S_TREASURE_BOX_PICK_UP_REQ);
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_RELIVE_REQ);
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_TAKE_BOSS_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_ATTACK_CITY_ENCOURAGE_REQ);

	// 无尽之地
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_DATA_REQ);
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_ENTER_REQ);
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_BATTLE_START_REQ);
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_BATTLE_OVER_REQ);
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_KILL_MONSTER_REQ);
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_COLLISION_REQ);
	DEFINE_MSG_PROC(C2S_ENDLESS_LAND_KEEP_KILL_REWARD_REQ);

	// 爵位
	DEFINE_MSG_PROC(C2S_NOBILITY_ACTIVATE_REQ);

	// 超值折扣
	DEFINE_MSG_PROC(C2S_SUPER_DISCOUNT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_SUPER_DISCOUNT_BUY_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_SUPER_DISCOUNT_ACCUMULATE_REWARD_REQ);

	// 超值折扣(新)
	DEFINE_MSG_PROC(C2S_NEW_SUPER_DISCOUNT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_NEW_SUPER_DISCOUNT_BUY_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_NEW_SUPER_DISCOUNT_ACCUMULATE_REWARD_REQ);

	// 节日活动
	DEFINE_MSG_PROC(C2S_FESTIVAL_ACTIVITY_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_FESTIVAL_ACTIVITY_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_FESTIVAL_ACTIVITY_GOODS_EXCHANGE_REQ);
	DEFINE_MSG_PROC(C2S_FESTIVAL_ACTIVITY_RED_POINT_REQ);

	// 精准推荐
	DEFINE_MSG_PROC(C2S_ACCURATE_RECOMMEND_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_ACCURATE_RECOMMEND_GIFT_REQ);

	// 宝石
	DEFINE_MSG_PROC(C2S_GEM_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GEM_COMPOSE_REQ);
	DEFINE_MSG_PROC(C2S_GEM_INLAY_REQ);
	DEFINE_MSG_PROC(C2S_GEM_UNLOAD_REQ);
	DEFINE_MSG_PROC(C2S_GEM_HOLE_OPEN_REQ);
	DEFINE_MSG_PROC(C2S_GEM_DECOMPOSE_REQ);

	// 组队
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_ANSWER_QUESTION_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_DIALOG_OVER_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_NEXT_NPC_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_BOSS_TASK_START_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_LOTTERY_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_LEAVE_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_CREATE_TEAM_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_INVITE_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_ACCEPT_INVITE_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_RECOMMEND_LIST_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_MATCH_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_CANCEL_MATCH_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_ACCEPT_TASK_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_TASK_START_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_RANK_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_SHORTCUT_CHAT_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_LOTTERY_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_TEAM_DUNGEON_JOIN_IN_REQ);

	// 登录奖励
	DEFINE_MSG_PROC(C2S_LOGIN_REWARD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_LOGIN_REWARD_REQ);

	// 王者赛
	DEFINE_MSG_PROC(C2S_KING_MATCH_DATA_REQ);
	DEFINE_MSG_PROC(C2S_KING_MATCH_SEARCH_TARGET_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_KING_MATCH_TASK_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_KING_MATCH_SEASON_RANK_REQ);

	// 圣诞节
	DEFINE_MSG_PROC(C2S_CHRISTMAS_DATA_REQ);
	DEFINE_MSG_PROC(C2S_CHRISTMAS_BATTLE_ENTER_REQ);
	DEFINE_MSG_PROC(C2S_CHRISTMAS_BATTLE_LEAVE_REQ);
	DEFINE_MSG_PROC(C2S_CHRISTMAS_ATTACK_BOSS_REQ);
	DEFINE_MSG_PROC(C2S_CHRISTMAS_TAKE_BOSS_REWARD_REQ);

	// facebook活动
	DEFINE_MSG_PROC(C2S_FACEBOOK_ACTIVITY_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_FACEBOOK_ACCOUNT_BINDING_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_FACEBOOK_SHARE_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_FACEBOOK_FRIEND_INVITE_REQ);
	DEFINE_MSG_PROC(C2S_FACEBOOK_FRIEND_SUMMON_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_FACEBOOK_FRIEND_INVITE_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_FACEBOOK_FRIEND_SUMMON_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_FACEBOOK_FRIEND_INVITE_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_FACEBOOK_COMMEND_REWARD_REQ);

	// 在线奖励
	DEFINE_MSG_PROC(C2S_ONLINE_REWARD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_ONLINE_REWARD_REQ);

	// 7天登录
	DEFINE_MSG_PROC(C2S_SEVEN_DAY_LOGIN_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_SEVEN_DAY_LOGIN_REWARD_REQ);

	// 充值回馈
	DEFINE_MSG_PROC(C2S_RECHARGE_REWARD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_RECHARGE_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_RECHARGE_EXTRA_REWARD_REQ);
	
	// 累充奖励
	DEFINE_MSG_PROC(C2S_TOTAL_RECHARGE_REWARD_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_TOTAL_RECHARGE_REWARD_REQ);

	// 扭蛋抽奖
	DEFINE_MSG_PROC(C2S_ND_LOTTERY_REQ);
	DEFINE_MSG_PROC(C2S_ND_LOTTERY_RECORD_REQ);

	// 热卖商品
	DEFINE_MSG_PROC(C2S_HOT_SALE_GOODS_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_HOT_SALE_GOODS_RECHARGE_REWARD_REQ);

	// 转盘
	DEFINE_MSG_PROC(C2S_TURNTABLE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TURNTABLE_LOTTERY_REQ);

	// 阵营招募
	DEFINE_MSG_PROC(C2S_CAMP_RECRUIT_DATA_REQ);
	DEFINE_MSG_PROC(C2S_CAMP_RECRUIT_REQ);
	DEFINE_MSG_PROC(C2S_CAMP_RECRUIT_SCORE_TASK_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_CAMP_RECRUIT_RECORD_REQ);

	// unlock活动
	DEFINE_MSG_PROC(C2S_UNLOCK_ACTIVITY_DATA_REQ);
	DEFINE_MSG_PROC(C2S_SHOP_SCORE_FINISH_REQ);
	DEFINE_MSG_PROC(C2S_WATCHING_VIDEO_NOTIFY_REQ);

	// 世界等级任务
	DEFINE_MSG_PROC(C2S_WORLD_LEVEL_TASK_DATA_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_WORLD_LEVEL_TASK_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_TAKE_WORLD_LEVEL_TASK_FINAL_REWARD_REQ);

	// 资源战
	DEFINE_MSG_PROC(C2S_PLAYER_RESOURCE_WAR_DATA_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_ENEMY_LIST_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_BATTLE_RECORD_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_GIVE_UP_OCCUPY_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_KEEP_OCCUPY_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_CHAPTER_DATA_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_SAME_RESOURCE_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_GUILD_RESOURCE_REQ);
	DEFINE_MSG_PROC(C2S_RESOURCE_WAR_TECHNOLOGY_UPGRADE_REQ);

	// 军团战
	DEFINE_MSG_PROC(C2S_GUILD_WAR_ROLE_DATA_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_OCCUPY_STAR_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_DECLARE_WAR_STAR_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_STAR_LIST_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_DECLARE_WAR_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_ORGANIZE_DEFENSE_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_EVACUATE_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_BUY_HIGH_STAR_BATTLE_TIMES_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_TAKE_STAR_REWARD_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_STAR_DETAIL_REQ);
	DEFINE_MSG_PROC(C2S_GUILD_WAR_TOWER_LIST_REQ);

	// 挂机
	DEFINE_MSG_PROC(C2S_HANG_UP_DROP_DATA_REQ);
	DEFINE_MSG_PROC(C2S_HANG_UP_DROP_REWARD_OBTAIN_REQ);
	

	//其他
	DEFINE_MSG_PROC(C2S_HEART_BEAT_REQ);					// 心跳(用户与逻辑服)
	DEFINE_MSG_PROC(C2S_SERVER_TIME_REQ);
	DEFINE_MSG_PROC(C2S_GUIDE_UPDATE_REQ);

	/*--------------------------------------------------------------------------------------------------------------------------*/
	//来自Gate
	DEFINE_MSG_PROC(G2M_CLIENT_DISCONNECT_CMD);
	DEFINE_MSG_PROC(G2M_HEART_BEAT);					// 心跳(网关与逻辑服)
};
