#include "stdafx.h"
#include <WinSock2.h>
#include <stdio.h>
#include "MsgRegister.h"


//消息注册
MsgRegister::MsgRegister()
{
#define ADD_MSG(X){AddMsg(X,new (MSG_##X)());}
	/*--------------------------------------------------------------------------------------------------------------------------*/
	// 1) 客户端和GateSvr之间消息注册
	/*--------------------------------------------------------------------------------------------------------------------------*/

	/*--------------------------------------------------------------------------------------------------------------------------*/
	// 2) 客户端和MapSvr之间消息注册
	/*--------------------------------------------------------------------------------------------------------------------------*/

	// 登录,角色
	ADD_MSG(C2S_LOGIN_ACCOUNT_REQ);
	ADD_MSG(C2S_LOGIN_SELECT_SERVER_REQ);
	ADD_MSG(C2S_LOGIN_CREATE_ROLE_REQ);
	ADD_MSG(S2C_ROLE_INFO_NOTIFY);
	ADD_MSG(C2S_ROLE_DETAILS_REQ);
	ADD_MSG(S2C_ROLE_DETAILS_RESP);
	ADD_MSG(S2C_ROLE_PROPERTY_NOTIFY);
	ADD_MSG(C2S_ROLE_PRO_RECOVER_REQ);
	ADD_MSG(S2C_ROLE_PRO_RECOVER_RESP);
	ADD_MSG(C2S_HEAD_IMAGE_REPLACE_REQ);
	ADD_MSG(S2C_HEAD_IMAGE_REPLACE_RESP);
	ADD_MSG(C2S_ROLE_NAME_MODIFY_REQ);
	ADD_MSG(S2C_ROLE_NAME_MODIFY_RESP);
	ADD_MSG(S2C_ROLE_LEVEL_UP_NOTIFY);
	ADD_MSG(S2C_SYSTEM_NOTICE);
	ADD_MSG(C2S_START_GAME_REQ);
	ADD_MSG(S2C_START_GAME_RESP);

	ADD_MSG(S2C_LOGIN_ACCOUNT_RESP);
	ADD_MSG(S2C_LOGIN_SELECT_SERVER_RESP);
	ADD_MSG(S2C_LOGIN_CREATE_ROLE_RESP);
	ADD_MSG(S2C_LOGIN_ENTER_GAME_NOTIFY);
	//ADD_MSG(S2C_LOGIN_ROLE_INFO_NOTIFY);
	ADD_MSG(C2S_ACCOUNT_REGISTER_REQ);
	ADD_MSG(S2C_ACCOUNT_REGISTER_RESP);
	ADD_MSG(C2S_ACCOUNT_PASSWORD_CHANGE_REQ);
	ADD_MSG(S2C_ACCOUNT_PASSWORD_CHANGE_RESP);
	ADD_MSG(C2S_TAKE_ACTIVITY_GIFT_REQ);
	ADD_MSG(S2C_TAKE_ACTIVITY_GIFT_RESP);
	ADD_MSG(C2S_ACTIVITY_NOTICE_REQ);
	ADD_MSG(S2C_ACTIVITY_NOTICE_RESP);
	ADD_MSG(C2S_AUTHENTICATION_CODE_REQ);
	ADD_MSG(C2S_MOBILE_BIND_REQ);
	ADD_MSG(S2C_NEW_DAY_NOTIFY);
	ADD_MSG(C2S_SDK_LOGIN_REQ);
	ADD_MSG(S2C_SDK_LOGIN_RESP);
	ADD_MSG(C2S_SDK_ORDER_ID_REQ);
	ADD_MSG(S2C_SDK_ORDER_ID_RESP);
	ADD_MSG(C2S_RECHARGE_SUCCESS_REPORT_REQ);
	ADD_MSG(S2C_RECHARGE_SUCCESS_REPORT_RESP);
	ADD_MSG(C2S_HERO_GOTO_REQ);
	ADD_MSG(S2C_HERO_GOTO_RESP);
	ADD_MSG(S2C_HERO_GOTO_NOTIFY);
	ADD_MSG(C2S_ENTER_SCENE_REQ);
	ADD_MSG(S2C_ENTER_SCENE_RESP);
	ADD_MSG(S2C_ENTER_SCENE_NOTICE);
	ADD_MSG(C2S_LEAVE_SCENE_REQ);
	ADD_MSG(S2C_LEAVE_SCENE_RESP);
	ADD_MSG(S2C_LEAVE_SCENE_NOTICE);
	ADD_MSG(S2C_CLIENT_UPDATE_NOTIFY);
 	ADD_MSG(C2S_SCENE_ITEM_LOCK_REQ);
 	ADD_MSG(S2C_SCENE_ITEM_LOCK_RESP);
 	ADD_MSG(C2S_SCENE_ITEM_PICK_UP_REQ);
 	ADD_MSG(S2C_SCENE_ITEM_PICK_UP_RESP);
	ADD_MSG(S2C_SCENE_ITEM_LOCK_NOTIFY);
	//ADD_MSG(S2C_SCENE_ITEM_PICK_UP_RESP);
	ADD_MSG(C2S_LOGIN_REQ);
	ADD_MSG(S2C_LOGIN_RESP);
	ADD_MSG(C2S_NEW_ROLE_GUIDE_UPDATE_REQ);



	// 战斗
	ADD_MSG(C2S_BATTLE_START_REQ);
	ADD_MSG(S2C_BATTLE_START_RESP);
	ADD_MSG(C2S_BATTLE_END_REQ);
	ADD_MSG(S2C_BATTLE_END_RESP);
	ADD_MSG(C2S_HELP_BATTLE_TARGET_REQ);
	ADD_MSG(S2C_HELP_BATTLE_TARGET_RESP);

	// 排行榜
	ADD_MSG(C2S_RANK_LIST_REQ);
	ADD_MSG(S2C_RANK_LIST_RESP);
	ADD_MSG(C2S_RANK_LIKE_REQ);
	ADD_MSG(S2C_RANK_LIKE_RESP);
	ADD_MSG(C2S_RANK_LEAVE_MESSAGE_REQ);
	ADD_MSG(S2C_RANK_LEAVE_MESSAGE_RESP);
	ADD_MSG(C2S_RANK_LEAVE_MESSAGE_LIST_REQ);
	ADD_MSG(S2C_RANK_LEAVE_MESSAGE_LIST_RESP);
	ADD_MSG(C2S_GUILD_RANK_LIST_REQ);
	ADD_MSG(S2C_GUILD_RANK_LIST_RESP);
	ADD_MSG(C2S_MY_RANK_REQ);
	ADD_MSG(S2C_MY_RANK_RESP);

	// 聊天
	ADD_MSG(C2S_CHAT_REQ);
	ADD_MSG(S2C_CHAT_RESP);
	ADD_MSG(S2C_CHAT_NOTIFY);
	ADD_MSG(C2S_CHAT_VOICE_REQ);
	ADD_MSG(S2C_CHAT_VOICE_RESP);
	ADD_MSG(C2S_CHAT_RECORD_LIST_REQ);
	ADD_MSG(S2C_CHAT_RECORD_LIST_RESP);

	ADD_MSG(C2M_GM_REQ)

	// 商店
	ADD_MSG(C2S_SHOP_GOODS_BUY_REQ);
	ADD_MSG(S2C_SHOP_GOODS_BUY_RESP);
	ADD_MSG(C2S_SHOP_GOODS_BUY_RECORD_REQ);
	ADD_MSG(S2C_SHOP_GOODS_BUY_RECORD_RESP);
	ADD_MSG(C2S_SHOP_GOODS_SELL_REQ);
	ADD_MSG(S2C_SHOP_GOODS_SELL_RESP);
	ADD_MSG(C2S_SHOP_LIMIT_GOODS_LIST_REQ);
	ADD_MSG(S2C_SHOP_LIMIT_GOODS_LIST_RESP);
	ADD_MSG(C2S_SHOP_REFRESH_REQ);
	ADD_MSG(S2C_SHOP_REFRESH_RESP);
	ADD_MSG(C2S_HERO_SHOP_DATA_REQ);
	ADD_MSG(S2C_HERO_SHOP_DATA_RESP);
	ADD_MSG(C2S_AWAKEN_SHOP_DATA_REQ);
	ADD_MSG(S2C_AWAKEN_SHOP_DATA_RESP);
	ADD_MSG(C2S_STAR_SOUL_SHOP_DATA_REQ);
	ADD_MSG(S2C_STAR_SOUL_SHOP_DATA_RESP);
	ADD_MSG(C2S_DIRECT_SHOP_DATA_REQ);
	ADD_MSG(S2C_DIRECT_SHOP_DATA_RESP);
	ADD_MSG(C2S_TAKE_DIRECT_BUY_GOODS_REQ);
	ADD_MSG(S2C_TAKE_DIRECT_BUY_GOODS_RESP);
	ADD_MSG(C2S_CRYSTAL_SHOP_DATA_REQ);
	ADD_MSG(S2C_CRYSTAL_SHOP_DATA_RESP);

	// 副本
	ADD_MSG(C2S_FB_MAIN_DATA_REQ);
	ADD_MSG(S2C_FB_MAIN_DATA_RESP);
	ADD_MSG(C2S_FB_AWARD_GET_REQ);
	ADD_MSG(S2C_FB_AWARD_GET_RESP);
	ADD_MSG(C2S_FB_DAILY_DATA_REQ);
	ADD_MSG(S2C_FB_DAILY_DATA_RESP);
	ADD_MSG(C2S_FB_HERO_DATA_REQ);
	ADD_MSG(S2C_FB_HERO_DATA_RESP);
	ADD_MSG(C2S_FB_CLEAN_REQ);
	ADD_MSG(S2C_FB_CLEAN_RESP);
	ADD_MSG(C2S_FB_ELITE_DATA_REQ);
	ADD_MSG(S2C_FB_ELITE_DATA_RESP);
	ADD_MSG(C2S_FB_RESET_REQ);
	ADD_MSG(S2C_FB_RESET_RESP);
	ADD_MSG(C2S_FB_ONE_KEY_TAKE_REWARD_REQ);
	ADD_MSG(S2C_FB_ONE_KEY_TAKE_REWARD_RESP);
	ADD_MSG(C2S_TAKE_MAIN_FB_CHAPTER_REWARD_REQ);
	ADD_MSG(S2S_TAKE_MAIN_FB_CHAPTER_REWARD_RESP);

	// 爬塔
	ADD_MSG(C2S_TOWER_DATA_REQ);
	ADD_MSG(S2C_TOWER_DATA_RESP);

	ADD_MSG(C2S_TOWER_BUY_TIMES_REQ);
	ADD_MSG(S2C_TOWER_BUY_TIMES_RESP);
	ADD_MSG(C2S_TOWER_RESET_REQ);
	ADD_MSG(S2C_TOWER_RESET_RESP);
	ADD_MSG(C2S_TOWER_SELECT_PRO_REQ);
	ADD_MSG(S2C_TOWER_SELECT_PRO_RESP);
	ADD_MSG(C2S_TOWER_BUY_STAR_GOODS_REQ);
	ADD_MSG(S2C_TOWER_BUY_STAR_GOODS_RESP);
	ADD_MSG(C2S_TOWER_ONE_KEY_CLEAN_REQ);
	ADD_MSG(S2C_TOWER_ONE_KEY_CLEAN_RESP);

	// 领地
	ADD_MSG(C2S_PLAYER_LAND_DATA_REQ);
	ADD_MSG(C2S_LAND_PATROL_REQ);
	ADD_MSG(C2S_LAND_VIEW_PATROL_AWARD_REQ);
	ADD_MSG(C2S_LAND_GET_PATROL_AWARD_REQ);
	ADD_MSG(C2S_LAND_SKILL_LEVELUP_REQ);
	ADD_MSG(C2S_LAND_SUPPRESS_RIOT_REQ);
	ADD_MSG(C2S_FRIEND_LAND_LIST_REQ);
	ADD_MSG(C2S_LAND_CITY_DETAILS_REQ);
	ADD_MSG(S2C_PLAYER_LAND_DATA_RESP);
	ADD_MSG(S2C_LAND_PATROL_RESP);
	ADD_MSG(S2C_LAND_VIEW_PATROL_AWARD_RESP);
	ADD_MSG(S2C_LAND_GET_PATROL_AWARD_RESP);
	ADD_MSG(S2C_LAND_SKILL_LEVELUP_RESP);
	ADD_MSG(S2C_LAND_SUPPRESS_RIOT_RESP);
	ADD_MSG(S2C_FRIEND_LAND_LIST_RESP);
	ADD_MSG(S2C_LAND_CITY_DETAILS_RESP);

	// 精灵
	ADD_MSG(C2S_SPIRIT_DATA_REQ);
	ADD_MSG(S2C_SPIRIT_DATA_RESP);
	ADD_MSG(C2S_HEART_OF_WORLD_LEVEL_UP_REQ);
	ADD_MSG(S2C_HEART_OF_WORLD_LEVEL_UP_RESP);
	ADD_MSG(C2S_SPIRIT_ENHANCE_REQ);
	ADD_MSG(S2C_SPIRIT_ENHANCE_RESP);
	ADD_MSG(C2S_SPIRIT_USE_REQ);
	ADD_MSG(S2C_SPIRIT_USE_RESP);
	ADD_MSG(C2S_HEART_OF_WORLD_DATA_REQ);
	ADD_MSG(S2C_HEART_OF_WORLD_DATA_RESP);
	ADD_MSG(C2S_SPIRIT_TRAIN_REQ);
	ADD_MSG(S2C_SPIRIT_TRAIN_RESP);
	ADD_MSG(C2S_SPRITE_STAR_UP_REQ);
	ADD_MSG(S2C_SPRITE_STAR_UP_RESP);
	ADD_MSG(C2S_SPRITE_BLESS_REQ);
	ADD_MSG(S2C_SPRITE_BLESS_RESP);
	ADD_MSG(C2S_SPRITE_COMPOSE_REQ);
	ADD_MSG(S2C_SPRITE_COMPOSE_RESP);


	// 工会
	ADD_MSG(C2S_GUILD_DATE_REQ)					// 工会数据请求
	ADD_MSG(S2C_GUILD_DATE_RESP)				// 工会数据响应
	ADD_MSG(C2S_GUILD_CREATE_REQ)				// 创建工会
	ADD_MSG(S2C_GUILD_CREATE_RESP)				// 创建工会响应
	ADD_MSG(C2S_GUILD_DISMISS_REQ)				// 解散工会
	ADD_MSG(S2C_GUILD_DISMISS_RESP)				// 解散工会响应
	ADD_MSG(C2S_GUILD_APPLY_REQ)				// 申请加入工会
	ADD_MSG(S2C_GUILD_APPLY_RESP)				// 申请加入工会响应
	ADD_MSG(C2S_GUILD_APPLY_CHECK_REQ)			// 审核申请
	ADD_MSG(S2C_GUILD_APPLY_CHECK_RESP)			// 审核申请响应
	ADD_MSG(C2S_GUILD_APPLY_CANCEL_REQ)			// 取消申请		
	ADD_MSG(S2C_GUILD_APPLY_CANCEL_RESP)		// 取消申请响应
	ADD_MSG(C2S_GUILD_KICKOUT_REQ)				// 踢出工会
	ADD_MSG(S2C_GUILD_KICKOUT_RESP)				// 踢出工会响应
	ADD_MSG(C2S_GUILD_LEAVE_REQ)				// 退出工会
	ADD_MSG(S2C_GUILD_LEAVE_RESP)				// 退出工会响应
	ADD_MSG(C2S_GUILD_APPOINT_REQ)				// 任命
	ADD_MSG(S2C_GUILD_APPOINT_RESP)				// 任命响应
	ADD_MSG(C2S_GUILD_LEAVE_MESSAGE_REQ)		// 留言	
	ADD_MSG(S2C_GUILD_LEAVE_MESSAGE_RESP)		// 留言响应
	ADD_MSG(C2S_GUILD_SEARCH_REQ)				// 搜索工会
	ADD_MSG(S2C_GUILD_SEARCH_RESP)				// 搜索工会响应
	ADD_MSG(C2S_GUILD_QY_REQ)					// 泉涌
	ADD_MSG(S2C_GUILD_QY_RESP)					// 泉涌响应
	ADD_MSG(C2S_GUILD_QS_AWARD_REQ)				// 冰泉奖励领取	
	ADD_MSG(S2C_GUILD_QS_AWARD_RESP)			// 冰泉奖励领取	
	ADD_MSG(C2S_GUILD_APPLY_LIST_REQ)			// 申请列表请求				
	ADD_MSG(S2C_GUILD_APPLY_LIST_RESP)			// 申请列表响应
	ADD_MSG(C2S_GUILD_LEAVEMSG_LIST_REQ)		// 留言列表请求
	ADD_MSG(S2C_GUILD_LEAVEMSG_LIST_RESP)		// 留言列表响应
	ADD_MSG(C2S_GUILD_MEMBER_LIST_REQ)			// 成员列表请求
	ADD_MSG(S2C_GUILD_MEMBER_LIST_RESP)			// 成员列表响应
	ADD_MSG(C2S_GUILD_LIST_REQ)					// 工会列表请求
	ADD_MSG(S2C_GUILD_LIST_RESP)				// 工会列表响应
	ADD_MSG(C2S_GUILD_INFO_MODIFY_REQ)			// 修改工会信息请求
	ADD_MSG(S2C_GUILD_INFO_MODIFY_RESP)			// 修改工会信息响应
	ADD_MSG(C2S_GUILD_EVENT_LIST_REQ)
	ADD_MSG(S2C_GUILD_EVENT_LIST_RESP)
	ADD_MSG(C2S_GUILD_SKILL_LIST_REQ);
	ADD_MSG(S2C_GUILD_SKILL_LIST_RESP);
	ADD_MSG(C2S_GUILD_SKILL_LEVEL_UP_REQ);
	ADD_MSG(S2C_GUILD_SKILL_LEVEL_UP_RESP);
	ADD_MSG(C2S_GUILD_FB_DATA_REQ);
	ADD_MSG(S2C_GUILD_FB_DATA_RESP);
	ADD_MSG(C2S_GUILD_FB_CHAPTER_REWARD_REQ);
	ADD_MSG(S2C_GUILD_FB_CHAPTER_REWARD_RESP);
	ADD_MSG(C2S_GUILD_FB_MAP_REWARD_REQ);
	ADD_MSG(S2C_GUILD_FB_MAP_REWARD_RESP);
	ADD_MSG(C2S_GUILD_FB_MAP_REWARD_RECORD_REQ);
	ADD_MSG(S2C_GUILD_FB_MAP_REWARD_RECORD_RESP);
	ADD_MSG(C2S_GUILD_FB_DAMAGE_RECORD_REQ);
	ADD_MSG(S2C_GUILD_FB_DAMAGE_RECORD_RESP);
	ADD_MSG(C2S_GUILD_FB_BATTLE_TIMES_BUY_REQ);
	ADD_MSG(S2C_GUILD_FB_BATTLE_TIMES_BUY_RESP);
	ADD_MSG(C2S_GUILD_IMPEACH_REQ);
	ADD_MSG(S2C_GUILD_IMPEACH_RESP);
	ADD_MSG(C2S_GUILD_MONSTER_DATA_REQ);
	ADD_MSG(S2C_GUILD_MONSTER_DATA_RESP);
	ADD_MSG(C2S_GUILD_FB_CHAPTER_RESET_REQ);
	ADD_MSG(S2C_GUILD_FB_CHAPTER_RESET_RESP);
	ADD_MSG(C2S_GUILD_MY_MAP_REWARD_RECORD_REQ);
	ADD_MSG(S2C_GUILD_MY_MAP_REWARD_RECORD_RESP);
	ADD_MSG(S2C_GUILD_IMPEACH_NOTICE);


	// 成就
	ADD_MSG(C2S_ACHIEVEMENT_LIST_REQ);			// 成就列表请求
	ADD_MSG(S2C_ACHIEVEMENT_LIST_RESP);			// 成就列表响应	
	ADD_MSG(S2C_ACHIEVEMENT_DATA_NOTIFY);		// 成就数据通知
	ADD_MSG(C2S_ACHIEVEMENT_AWARD_REQ);			// 成就奖励领取请求
	ADD_MSG(S2C_ACHIEVEMENT_AWARD_RESP);		// 成就奖励领取响应

	// 日常任务
	ADD_MSG(C2S_DAILY_MISSION_LIST_REQ);
	ADD_MSG(S2C_DAILY_MISSION_LIST_RESP);
	ADD_MSG(C2S_DAILY_MISSION_AWARD_REQ);
	ADD_MSG(S2C_DAILY_MISSION_AWARD_RESP);
	ADD_MSG(C2S_DAILY_MISSION_POINT_AWARD_REQ);
	ADD_MSG(S2C_DAILY_MISSION_POINT_AWARD_RESP);
	ADD_MSG(S2C_DAILY_MISSION_DATA_NOTIFY);

	// 世界BOSS
	ADD_MSG(C2S_WORLD_BOSS_DATA_REQ);
	ADD_MSG(S2C_WORLD_BOSS_DATA_RESP);
	ADD_MSG(C2S_WORLD_BOSS_SELECT_CAMP_REQ);
	ADD_MSG(S2C_WORLD_BOSS_SELECT_CAMP_RESP);
	ADD_MSG(C2S_WORLD_BOSS_REWARD_REQ);
	ADD_MSG(S2C_WORLD_BOSS_REWARD_RESP);
	ADD_MSG(C2S_WORLD_BOSS_REWARD_RECORD_REQ);
	ADD_MSG(S2C_WORLD_BOSS_REWARD_RECORD_RESP);
	ADD_MSG(C2S_WORLD_BOSS_BATTLE_RECORD_REQ);
	ADD_MSG(S2C_WORLD_BOSS_BATTLE_RECORD_RESP);
	ADD_MSG(C2S_WORLD_BOSS_BATTLE_TIMES_BUY_REQ);
	ADD_MSG(S2C_WORLD_BOSS_BATTLE_TIMES_BUY_RESP);
	ADD_MSG(S2C_WORLD_BOSS_DAMAGE_NOTIFY);
	ADD_MSG(S2C_WORLD_BOSS_ACTIVITY_START_NOTIFY);
	ADD_MSG(S2C_WORLD_BOSS_ACTIVITY_OVER_NOTIFY);

	// 竞技场
	ADD_MSG(C2S_ARENA_TARGET_LIST_REQ);
	ADD_MSG(S2C_ARENA_TARGET_LIST_RESP);
	ADD_MSG(C2S_ARENA_BATTLE_RECORD_REQ);
	ADD_MSG(S2C_ARENA_BATTLE_RECORD_RESP);

	// 物品
	ADD_MSG(C2S_ITEM_LIST_REQ);
	ADD_MSG(C2S_ITEM_USE_REQ);
	ADD_MSG(S2C_ITEM_LIST_RESP);
	ADD_MSG(S2C_ITEM_USE_RESP);
	ADD_MSG(S2C_ITEM_DATA_NOTIFY);
	ADD_MSG(C2S_ITEM_FP_REQ);
	ADD_MSG(S2C_ITEM_FP_RESP);
	ADD_MSG(C2S_ITEM_COMPOSE_REQ);
	ADD_MSG(S2C_ITEM_COMPOSE_RESP);
	ADD_MSG(C2S_ITEM_DECOMPOSE_REQ);
	ADD_MSG(S2C_ITEM_DECOMPOSE_RESP);

	// 邮件
	ADD_MSG(C2S_EMAIL_LIST_REQ);
	ADD_MSG(S2C_EMAIL_LIST_RESP);
	ADD_MSG(S2C_EMAIL_NEW_NOTIFY);

	// 装备
	ADD_MSG(C2S_EQUIPMENT_LIST_REQ);
	ADD_MSG(S2C_EQUIPMENT_LIST_RESP);
	ADD_MSG(C2S_EQUIPMENT_INFO_REQ);
	ADD_MSG(S2C_EQUIPMENT_INFO_RESP);
	ADD_MSG(C2S_EQUIPMENT_COMPOSE_REQ);
	ADD_MSG(S2C_EQUIPMENT_COMPOSE_RESP);
	ADD_MSG(S2C_EQUIPMENT_INFO_NOTIFY);
	ADD_MSG(C2S_EQUIPMENT_STRENG_REQ);
	ADD_MSG(S2C_EQUIPMENT_STRENG_RESP);
	ADD_MSG(C2S_EQUIPMENT_REFINE_REQ);
	ADD_MSG(S2C_EQUIPMENT_REFINE_RESP);
	ADD_MSG(C2S_EQUIPMENT_PUT_ON_REQ);
	ADD_MSG(S2C_EQUIPMENT_PUT_ON_RESP);
	ADD_MSG(C2S_EQUIPMENT_ONE_KEY_ENHANCE_REQ);
	ADD_MSG(S2C_EQUIPMENT_ONE_KEY_ENHANCE_RESP);
	ADD_MSG(C2S_EQUIPMENT_STAR_UP_REQ);
	ADD_MSG(S2C_EQUIPMENT_STAR_UP_RESP);
	ADD_MSG(C2S_EQUIPMENT_QUALITY_UP_REQ);
	ADD_MSG(S2C_EQUIPMENT_QUALITY_UP_RESP);


	// 宝物
	ADD_MSG(C2S_TREASURE_LIST_REQ);				// 宝物列表请求
	ADD_MSG(S2C_TREASURE_LIST_RESP);			// 宝物列表响应
	ADD_MSG(C2S_TREASURE_STRENGTHEN_REQ);		// 宝物强化
	ADD_MSG(S2C_TREASURE_STRENGTHEN_RESP);		// 宝物强化响应
	ADD_MSG(C2S_TREASURE_REFINE_REQ);			// 宝物精炼
	ADD_MSG(S2C_TREASURE_REFINE_RESP);			// 宝物精炼响应
	ADD_MSG(C2S_TREASURE_COMPOSE_REQ);			// 宝物合成
	ADD_MSG(S2C_TREASURE_COMPOSE_RESP);			// 宝物合成响应
	ADD_MSG(S2C_TREASURE_INFO_NOTIFY);			// 宝物信息通知
	ADD_MSG(C2S_TREASURE_PUT_ON_REQ);			// 穿戴宝物请求 
	ADD_MSG(S2C_TREASURE_PUT_ON_RESP);			// 穿戴宝物响应
	ADD_MSG(C2S_TREASURE_SMELT_REQ);
	ADD_MSG(S2C_TREASURE_SMELT_RESP);
	ADD_MSG(C2S_TREASURE_QUALITY_UP_REQ);
	ADD_MSG(S2C_TREASURE_QUALITY_UP_RESP);

	// 叛军
	ADD_MSG(C2S_REBEL_DATA_REQ);
	ADD_MSG(S2C_REBEL_DATA_RESP);
	ADD_MSG(C2S_REBEL_EXPLOIT_AWARD_REQ);
	ADD_MSG(S2C_REBEL_EXPLOIT_AWARD_RESP);
	ADD_MSG(C2S_REBEL_EXPLOIT_AWARD_RECORD_REQ);
	ADD_MSG(S2C_REBEL_EXPLOIT_AWARD_RECORD_RESP);
	ADD_MSG(C2S_REBEL_SHARE_REQ);
	ADD_MSG(S2C_REBEL_SHARE_RESP);
	ADD_MSG(S2C_REBEL_DISCOVER_NOTIFY);

	// 回收
	ADD_MSG(C2S_RECYCLE_DECOMPOSE_REQ);
	ADD_MSG(S2C_RECYCLE_DECOMPOSE_RESP);
	ADD_MSG(C2S_RECYCLE_RESET_REQ);
	ADD_MSG(S2C_RECYCLE_RESET_RESP);
	ADD_MSG(C2S_RECYCLE_DECOMPOSE_RETURN_REQ);
	ADD_MSG(S2C_RECYCLE_DECOMPOSE_RETURN_RESP);
	ADD_MSG(C2S_RECYCLE_RESET_RETURN_REQ);
	ADD_MSG(S2C_RECYCLE_RESET_RETURN_RESP);

	// 夺宝
	ADD_MSG(C2S_DUOBAO_DATA_REQ);
	ADD_MSG(S2C_DUOBAO_DATA_RESP);
	ADD_MSG(C2S_DUOBAO_TARGET_LIST_REQ);
	ADD_MSG(S2C_DUOBAO_TARGET_LIST_RESP);
	ADD_MSG(C2S_DUOBAO_FIVE_TIMES_REQ);
	ADD_MSG(S2C_DUOBAO_FIVE_TIMES_RESP);
	ADD_MSG(C2S_TAKE_DUOBAO_PROGRESS_REWARD_REQ);
	ADD_MSG(S2C_TAKE_DUOBAO_PROGRESS_REWARD_RESP);

	// 英雄
	ADD_MSG(C2S_HERO_BASE_LIST_REQ);
	ADD_MSG(S2C_HERO_BASE_LIST_RESP);
	ADD_MSG(C2S_HERO_INFO_REQ);
	ADD_MSG(S2C_HERO_INFO_RESP);
	ADD_MSG(C2S_HERO_TO_BATTLE_REQ);
	ADD_MSG(S2C_HERO_TO_BATTLE_RESP);
	ADD_MSG(C2S_HERO_COLLECTION_LIST_REQ);
	ADD_MSG(S2C_HERO_COLLECTION_LIST_RESP);
	ADD_MSG(C2S_HERO_COMPOSE_REQ);
	ADD_MSG(C2S_HERO_LEVEL_UP_REQ);
	ADD_MSG(S2C_HERO_LEVEL_UP_RESP);
	ADD_MSG(C2S_HERO_BREAK_REQ);
	ADD_MSG(S2C_HERO_BREAK_RESP);
	ADD_MSG(C2S_HERO_TRAIN_REQ);
	ADD_MSG(S2C_HERO_TRAIN_RESP);
	ADD_MSG(S2C_HERO_BASE_INFO_NOTIFY);
	ADD_MSG(S2C_FORMATION_LIST_NOTIFY);
	ADD_MSG(C2S_HERO_DESTINY_REQ);				// 天命(潜能)请求
	ADD_MSG(S2C_HERO_DESTINY_RESP);				// 天命(潜能)响应
	ADD_MSG(C2S_HERO_SELL_REQ);					// 出售请求
	ADD_MSG(S2C_HERO_SELL_RESP);				// 出售响应
	ADD_MSG(C2S_REINFORCEMENT_TO_BATTLE_REQ);	// 援军上阵
	ADD_MSG(S2C_REINFORCEMENT_TO_BATTLE_RESP);	// 援军上阵响应
	ADD_MSG(C2S_HERO_SUMMON_REQ);
	ADD_MSG(S2C_HERO_SUMMON_RESP);
	ADD_MSG(C2S_HERO_SUMMON_DATA_REQ);
	ADD_MSG(S2C_HERO_SUMMON_DATA_RESP);
	ADD_MSG(C2S_HERO_AWAKEN_REQ);
	ADD_MSG(C2S_HERO_EQUIP_AWAKEN_ITEM_REQ);
	ADD_MSG(S2C_HERO_EQUIP_AWAKEN_ITEM_RESP);
	ADD_MSG(C2S_HERO_TRAIN_REPLACE_REQ);
	ADD_MSG(S2C_HERO_TRAIN_REPLACE_RESP);
	ADD_MSG(C2S_HERO_TRAIN_REWARD_GET_REQ);
	ADD_MSG(S2C_HERO_TRAIN_REWARD_GET_RESP);
	ADD_MSG(C2S_HERO_EVOLUTION_REQ);
	ADD_MSG(S2C_HERO_EVOLUTION_RESP);
	ADD_MSG(C2S_HERO_VIP_SUMMON_REQ);
	ADD_MSG(S2C_HERO_VIP_SUMMON_RESP);

	// 好友
	ADD_MSG(C2S_FRIEND_LIST_REQ);			// 请求好友列表
	ADD_MSG(S2C_FRIEND_LIST_RESP);			// 请求好友列表响应				
	ADD_MSG(C2S_BLACK_LIST_REQ);			// 请求黑名单列表
	ADD_MSG(S2C_BLACK_LIST_RESP);			// 请求黑名单列表响应			
	ADD_MSG(C2S_FRIEND_APPLY_LIST_REQ);		// 请求申请列表
	ADD_MSG(S2C_FRIEND_APPLY_LIST_RESP);	// 请求申请列表响应				
	ADD_MSG(C2S_FRIEND_RECOMMEND_LIST_REQ);	// 请求推荐列表
	ADD_MSG(S2C_FRIEND_RECOMMEND_LIST_RESP);// 推荐列表响应
	ADD_MSG(C2S_FRIEND_ADD_REQ);			// 添加好友
	ADD_MSG(S2C_FRIEND_ADD_RESP);			// 添加好友响应					
	ADD_MSG(C2S_FRIEND_DEL_REQ);			// 删除好友
	ADD_MSG(S2C_FRIEND_DEL_RESP);			// 删除好友响应					
	ADD_MSG(C2S_FRIEND_APPLY_REPLY_REQ);	// 申请好友回复
	ADD_MSG(S2C_FRIEND_APPLY_REPLY_RESP);	// 申请好友回复响应
	ADD_MSG(C2S_BLACK_ADD_REQ);				// 添加黑名单
	ADD_MSG(S2C_BLACK_ADD_RESP);			// 添加黑名单响应
	ADD_MSG(C2S_BLACK_DEL_REQ);				// 删除黑名单
	ADD_MSG(S2C_BLACK_DEL_RESP);			// 删除黑名单响应
	ADD_MSG(C2S_FRIEND_ENERGY_GIVE_REQ);	// 赠送精力
	ADD_MSG(S2C_FRIEND_ENERGY_GIVE_RESP);	// 赠送精力响应
	ADD_MSG(C2S_FRIEND_ENERGY_GET_REQ);		// 领取精力
	ADD_MSG(S2C_FRIEND_ENERGY_GET_RESP);	// 领取精力响应
	ADD_MSG(C2S_FRIEND_TARGET_FIND_REQ);	// 查找目标
	ADD_MSG(S2C_FRIEND_TARGET_FIND_RESP);	// 查找目标响应

	// 奖励中心
	ADD_MSG(C2S_REWARD_CENTER_LIST_REQ);
	ADD_MSG(S2C_REWARD_CENTER_LIST_RESP);
	ADD_MSG(C2S_REWARD_CENTER_GET_REQ);
	ADD_MSG(S2C_REWARD_CENTER_GET_RESP);
	ADD_MSG(S2C_REWARD_NOTICE);

	// 签到
	ADD_MSG(C2S_SIGN_IN_DATA_REQ);
	ADD_MSG(S2C_SIGN_IN_DATA_RESP);
	ADD_MSG(C2S_SIGN_IN_REQ);
	ADD_MSG(S2C_SIGN_IN_RESP);
	ADD_MSG(C2S_LUXURY_SIGN_IN_DATA_REQ);
	ADD_MSG(S2C_LUXURY_SIGN_IN_DATA_RESP);
	ADD_MSG(C2S_TAKE_LUXURY_SIGN_IN_REWARD_REQ);
	ADD_MSG(S2C_TAKE_LUXURY_SIGN_IN_REWARD_RESP);

	// 迎财神
	ADD_MSG(C2S_YCS_DATA_REQ);
	ADD_MSG(S2C_YCS_DATA_RESP);
	ADD_MSG(C2S_YCS_REWARD_REQ);
	ADD_MSG(S2C_YCS_REWARD_RESP);

	// 铜雀台 
	ADD_MSG(C2S_TQT_DATA_REQ);
	ADD_MSG(S2C_TQT_DATA_RESP);
	ADD_MSG(C2S_TQT_REWARD_REQ);
	ADD_MSG(S2C_TQT_REWARD_RESP);

	// 7天
	ADD_MSG(C2S_SEVEN_DAY_TARGET_LIST_REQ);
	ADD_MSG(S2C_SEVEN_DAY_TARGET_LIST_RESP);
	ADD_MSG(C2S_SEVEN_DAY_GET_REWARD_REQ);
	ADD_MSG(S2C_SEVEN_DAY_GET_REWARD_RESP);
	ADD_MSG(S2C_SEVEN_DAY_TARGET_DATA_NOTICE);
	ADD_MSG(C2S_SEVEN_DAY_COMPLETION_REWARD_REQ);
	ADD_MSG(S2C_SEVEN_DAY_COMPLETION_REWARD_RESP);

	// 占卜
	ADD_MSG(C2S_PLAYER_ZHANBU_DATA_REQ);
	ADD_MSG(S2C_PLAYER_ZHANBU_DATA_RESP);
	ADD_MSG(C2S_CARD_LIST_REQ);
	ADD_MSG(S2C_CARD_LIST_RESP);
	ADD_MSG(C2S_CARD_LEVEL_UP_REQ);
	ADD_MSG(S2C_CARD_LEVEL_UP_RESP);
	ADD_MSG(C2S_CARD_BREAK_REQ);
	ADD_MSG(S2C_CARD_BREAK_RESP);
	ADD_MSG(C2S_FAIRY_RECRUIT_REQ);
	ADD_MSG(S2C_FAIRY_RECRUIT_RESP);
	ADD_MSG(C2S_FAIRY_POKEDEX_STAR_UP_REQ);
	ADD_MSG(S2C_FAIRY_POKEDEX_STAR_UP_RESP);
	ADD_MSG(C2S_FAIRY_POKEDEX_REVIVE_REQ);
	ADD_MSG(S2C_FAIRY_POKEDEX_REVIVE_RESP);
	ADD_MSG(C2S_FAIRY_MAP_REFRESH_REQ);
	ADD_MSG(S2C_FAIRY_MAP_REFRESH_RESP);
	ADD_MSG(C2S_FAIRY_ACHIEVEMENT_ACTIVATION_REQ);
	ADD_MSG(S2C_FAIRY_ACHIEVEMENT_ACTIVATION_RESP);
	ADD_MSG(C2S_CARD_REFRESH_REQ);
	ADD_MSG(S2C_CARD_REFRESH_RESP);
	ADD_MSG(C2S_OPEN_CARD_REQ);
	ADD_MSG(S2C_OPEN_CARD_RESP);
	ADD_MSG(C2S_LOW_CARD_GROUP_REFRESH_TIMES_UPDATE_REQ);
	ADD_MSG(S2C_LOW_CARD_GROUP_REFRESH_TIMES_UPDATE_RESP);
	ADD_MSG(C2S_CELLECTION_GROUP_ACTIVATE_REQ);
	ADD_MSG(S2C_CELLECTION_GROUP_ACTIVATE_RESP);
	ADD_MSG(C2S_CELLECTION_GROUP_STAR_UP_REQ);
	ADD_MSG(S2C_CELLECTION_GROUP_STAR_UP_RESP);
	ADD_MSG(C2S_COLLECTION_BOOK_LIST_REQ);
	ADD_MSG(S2C_COLLECTION_BOOK_LIST_RESP);
	ADD_MSG(C2S_CELLECTION_GROUP_RESET_REQ);
	ADD_MSG(S2C_CELLECTION_GROUP_RESET_RESP);
	ADD_MSG(C2S_COLLECTION_EQUIP_CARD_REQ);
	ADD_MSG(S2C_COLLECTION_EQUIP_CARD_RESP);
	ADD_MSG(C2S_COLLECTION_UNLOAD_CARD_REQ);
	ADD_MSG(S2C_COLLECTION_UNLOAD_CARD_RESP);
	ADD_MSG(C2S_ZHAN_BU_ACHIEVEMENT_ACIVATE_REQ);
	ADD_MSG(S2C_ZHAN_BU_ACHIEVEMENT_ACIVATE_RESP);

	// 积分赛
	ADD_MSG(C2S_SCORE_MATCH_DATA_REQ);
	ADD_MSG(S2C_SCORE_MATCH_DATA_RESP);
	ADD_MSG(C2S_SCORE_MATCH_SELECT_CAMP_REQ);
	ADD_MSG(S2C_SCORE_MATCH_SELECT_CAMP_RESP);
	ADD_MSG(C2S_SCORE_MATCH_REFRESH_TARGET_REQ);
	ADD_MSG(S2C_SCORE_MATCH_REFRESH_TARGET_RESP);
	ADD_MSG(C2S_SCORE_MATCH_BUY_BATTLE_TIMES_REQ);
	ADD_MSG(S2C_SCORE_MATCH_BUY_BATTLE_TIMES_RESP);
	ADD_MSG(C2S_SCORE_MATCH_TAKE_TASK_REWARD_REQ);
	ADD_MSG(S2C_SCORE_MATCH_TAKE_TASK_REWARD_RESP);

	// 争霸赛
	ADD_MSG(C2S_WARCRAFT_DATA_REQ);
	ADD_MSG(C2S_WARCRAFT_BUY_BATTLE_TIMES_REQ);
	ADD_MSG(C2S_WARCRAFT_TARGET_LIST_REQ);
	ADD_MSG(C2S_WARCRAFT_RANK_LIST_REQ);
	ADD_MSG(S2C_WARCRAFT_RANK_LIST_RESP);
	ADD_MSG(C2S_WARCRAFT_CHEER_REQ);
	ADD_MSG(S2C_WARCRAFT_CHEER_RESP);

	// 称号
	ADD_MSG(C2S_USE_TITLE_REQ);
	ADD_MSG(S2C_USE_TITLE_RESP);
	ADD_MSG(C2S_ROLE_TITLE_INFO_REQ);
	ADD_MSG(S2C_ROLE_TITLE_INFO_RESP);

	// 红点
	ADD_MSG(C2S_RED_POINT_LIST_REQ);
	ADD_MSG(S2C_RED_POINT_LIST_RESP);
	ADD_MSG(S2C_RED_POINT_NOTIFY);

	// VIP礼包
	ADD_MSG(C2S_VIP_GIFT_DATA_REQ);
	ADD_MSG(S2C_VIP_GIFT_DATA_RESP);
	ADD_MSG(C2S_VIP_DAILY_GIFT_GET_REQ);
	ADD_MSG(S2C_VIP_DAILY_GIFT_GET_RESP);
	ADD_MSG(C2S_VIP_WEEK_GIFT_BUY_REQ);
	ADD_MSG(S2C_VIP_WEEK_GIFT_BUY_RESP);
	ADD_MSG(C2S_TAKE_TODAY_RECOMMEND_REWARD_REQ);
	ADD_MSG(S2C_TAKE_TODAY_RECOMMEND_REWARD_RESP);

	// 等级礼包
	ADD_MSG(C2S_LEVEL_SHOP_ACTIVITY_DATA_REQ);

	// 开服基金
	ADD_MSG(C2S_OPEN_SERVER_FUND_DATA_REQ);
	ADD_MSG(S2C_OPEN_SERVER_FUND_DATA_RESP);
	ADD_MSG(C2S_OPEN_SERVER_FUND_BUY_REQ);
	ADD_MSG(S2C_OPEN_SERVER_FUND_BUY_RESP);
	ADD_MSG(C2S_OPEN_SERVER_FUND_REWARD_TAKE_REQ);
	ADD_MSG(S2C_OPEN_SERVER_FUND_REWARD_TAKE_RESP);
	ADD_MSG(C2S_ALL_PEOPLE_WELFARE_TAKE_REQ);
	ADD_MSG(S2C_ALL_PEOPLE_WELFARE_TAKE_RESP);

	// 限时优惠
	ADD_MSG(C2S_LIMIT_PREFERENTIAL_DATA_REQ);
	ADD_MSG(S2C_LIMIT_PREFERENTIAL_DATA_RESP);
	ADD_MSG(C2S_LIMIT_PREFERENTIAL_WELFARE_TAKE_REQ);
	ADD_MSG(S2C_LIMIT_PREFERENTIAL_WELFARE_TAKE_RESP);

	// 等级礼包
	ADD_MSG(C2S_LEVEL_GIFT_DATA_REQ);
	ADD_MSG(S2C_LEVEL_GIFT_DATA_RESP);
	ADD_MSG(C2S_TAKE_LEVEL_GIFT_REWARD_REQ);
	ADD_MSG(S2C_TAKE_LEVEL_GIFT_REWARD_RESP)

	// 次日奖励
	ADD_MSG(C2S_NEXT_DAY_REWARD_DATA_REQ);
	ADD_MSG(S2C_NEXT_DAY_REWARD_DATA_RESP);
	ADD_MSG(C2S_NEXT_DAY_REWARD_TAKE_REQ);
	ADD_MSG(S2C_NEXT_DAY_REWARD_TAKE_RESP);

	// 玩家留言
	ADD_MSG(C2S_PLAYER_LEVEL_MESSAGE_REQ);
	ADD_MSG(S2C_PLAYER_LEVEL_MESSAGE_RESP);

	// 关卡评论
	ADD_MSG(C2S_MAP_COMMENT_LIST_REQ);
	ADD_MSG(S2C_MAP_COMMENT_LIST_RESP);
	ADD_MSG(C2S_MAP_COMMENT_REQ);
	ADD_MSG(S2C_MAP_COMMENT_RESP);
	ADD_MSG(C2S_MAP_COMMENT_LIKE_REQ);
	ADD_MSG(S2C_MAP_COMMENT_LIKE_RESP);

	// 充值/月卡
	ADD_MSG(C2S_RECHARGE_DATA_REQ);
	ADD_MSG(S2C_RECHARGE_DATA_RESP);
	ADD_MSG(C2S_RECHARGE_REQ);
	ADD_MSG(S2C_RECHARGE_RESP);
	ADD_MSG(C2S_MONTH_CARD_DATA_REQ);
	ADD_MSG(S2C_MONTH_CARD_DATA_RESP);
	ADD_MSG(C2S_MONTH_CARD_BUY_REQ);
	ADD_MSG(S2C_MONTH_CARD_BUY_RESP);
	ADD_MSG(C2S_TAKE_MONTH_CARD_REWARD_REQ);
	ADD_MSG(S2C_TAKE_MONTH_CARD_REWARD_RESP);
	ADD_MSG(S2C_RECHARGE_NOTIFY_RESP);

	// PVP
	ADD_MSG(C2S_PVP_SEARCH_TARGET_REQ);
	ADD_MSG(S2C_PVP_SEARCH_TARGET_RESP);
	//ADD_MSG(C2S_PVP_STOP_SEARCH_TARGET_REQ);
	//ADD_MSG(C2S_PVP_STOP_SEARCH_TARGET_RESP);
	ADD_MSG(S2C_PVP_READY_NOTIFY);
	ADD_MSG(C2S_PVP_READY_FINISH_REQ);
	ADD_MSG(S2C_PVP_READY_FINISH_RESP);
	ADD_MSG(S2C_PVP_BATTLE_START_NOTIFY);
	ADD_MSG(S2C_PVP_BATTLE_OVER_NOTIFY);
	ADD_MSG(C2S_PVP_USE_SKILL_REQ);
	ADD_MSG(S2C_PVP_USE_SKILL_RESP);
	ADD_MSG(S2C_PVP_USE_SKILL_NOTIFY);
	ADD_MSG(C2S_PVP_CREATE_BUFF_REQ);
	ADD_MSG(C2S_PVP_HP_CHANGE_REQ);
	ADD_MSG(C2S_PVP_BATTLE_RESULT_REQ);
	ADD_MSG(S2C_PVP_BATTLE_RESULT_RESP);
	//ADD_MSG(C2S_PVP_POSITION_SYN_REQ);
	ADD_MSG(C2S_PVP_TAKE_BATTLE_REWARD_REQ);
	ADD_MSG(S2C_PVP_TAKE_BATTLE_REWARD_RESP);
	ADD_MSG(C2S_PLAYER_PVP_DATA_REQ);
	ADD_MSG(S2C_PLAYER_PVP_DATA_RESP);
	ADD_MSG(C2S_PVP_SELECT_SPRIT_SKILL_REQ);
	ADD_MSG(S2C_PVP_SELECT_SPRIT_SKILL_RESP);
	ADD_MSG(C2S_PVP_CANCEL_SEARCH_TARGET_REQ);
	ADD_MSG(S2C_PVP_CANCEL_SEARCH_TARGET_RESP);


	// 限时活动
	ADD_MSG(C2S_LIMIT_FIRST_RECHARGE_DATA_REQ);
	ADD_MSG(S2C_LIMIT_FIRST_RECHARGE_DATA_RESP);
	ADD_MSG(C2S_LIMIT_SINGLE_RECHARGE_DATA_REQ);
	//ADD_MSG(S2C_LIMIT_SINGLE_RECHARGE_DATA_RESP);
	ADD_MSG(C2S_LIMIT_ACCUMULATE_RECHARGE_DATA_REQ);
	//ADD_MSG(S2C_LIMIT_ACCUMULATE_RECHARGE_DATA_RESP);
	ADD_MSG(C2S_LIMIT_RECRUIT_DATA_REQ);
	//ADD_MSG(S2C_LIMIT_RECRUIT_DATA_RESP);
	ADD_MSG(C2S_TAKE_LIMIT_ACTIVITY_REWARD_REQ);
	ADD_MSG(S2C_TAKE_LIMIT_ACTIVITY_REWARD_RESP);

	// 攻城
	ADD_MSG(C2S_ATTACK_CITY_DATA_REQ);
	ADD_MSG(S2C_ATTACK_CITY_DATA_RESP);
	ADD_MSG(C2S_ATTACK_CITY_ENTER_REQ);
	ADD_MSG(S2C_ATTACK_CITY_ENTER_RESP);
	ADD_MSG(S2C_ATTACK_CITY_ENTER_NOTICE);
	ADD_MSG(C2S_ATTACK_CITY_LEAVE_REQ);
	ADD_MSG(S2C_ATTACK_CITY_LEAVE_RESP);
	ADD_MSG(S2C_ATTACK_CITY_LEAVE_NOTICE);
	ADD_MSG(C2S_ATTACK_CITY_GOTO_REQ);
	ADD_MSG(S2C_ATTACK_CITY_GOTO_RESP);
	ADD_MSG(S2C_ATTACK_CITY_GOTO_NOTICE);
	ADD_MSG(S2C_ATTACK_CITY_MONSTER_LIST_NOTICE);
	ADD_MSG(S2C_ATTACK_CITY_MONSTER_DATA_NOTICE);
	ADD_MSG(S2C_TREASURE_BOX_LIST_NOTICE);
	ADD_MSG(S2C_TREASURE_BOX_DISAPPEAR_NOTICE);
	ADD_MSG(C2S_TREASURE_BOX_LOCK_REQ);
	ADD_MSG(S2C_TREASURE_BOX_LOCK_RESP);
	ADD_MSG(C2S_TREASURE_BOX_PICK_UP_REQ);
	ADD_MSG(S2C_TREASURE_BOX_PICK_UP_RESP);
	ADD_MSG(C2S_ATTACK_CITY_RELIVE_REQ);
	ADD_MSG(S2C_ATTACK_CITY_RELIVE_RESP);
	ADD_MSG(C2S_ATTACK_CITY_TAKE_BOSS_REWARD_REQ);
	ADD_MSG(S2C_ATTACK_CITY_TAKE_BOSS_REWARD_RESP);
	ADD_MSG(C2S_ATTACK_CITY_ENCOURAGE_REQ);
	ADD_MSG(S2C_ATTACK_CITY_ENCOURAGE_RESP);
	ADD_MSG(S2C_ATTACK_CITY_TOP_RANK_LIST_NOTICE);
	ADD_MSG(S2C_ATTACK_CITY_RANK_UPDATE_NOTICE);
	ADD_MSG(S2C_ATTACK_CITY_ACTIVITY_START_NOTICE);
	ADD_MSG(S2C_ATTACK_CITY_ACTIVITY_OVER_NOTICE);

	// 无尽之地
	ADD_MSG(C2S_ENDLESS_LAND_DATA_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_DATA_RESP);
	ADD_MSG(C2S_ENDLESS_LAND_ENTER_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_ENTER_RESP);
	ADD_MSG(C2S_ENDLESS_LAND_BATTLE_START_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_BATTLE_START_RESP);
	ADD_MSG(C2S_ENDLESS_LAND_BATTLE_OVER_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_BATTLE_OVER_RESP);
	ADD_MSG(C2S_ENDLESS_LAND_KILL_MONSTER_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_KILL_MONSTER_RESP);
	ADD_MSG(C2S_ENDLESS_LAND_COLLISION_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_COLLISION_RESP);
	ADD_MSG(C2S_ENDLESS_LAND_KEEP_KILL_REWARD_REQ);
	ADD_MSG(S2C_ENDLESS_LAND_KEEP_KILL_REWARD_RESP);

	// 爵位
	ADD_MSG(C2S_NOBILITY_ACTIVATE_REQ);
	ADD_MSG(S2C_NOBILITY_ACTIVATE_RESP);

	// 超值折扣
	ADD_MSG(C2S_SUPER_DISCOUNT_DATA_REQ);
	ADD_MSG(S2C_SUPER_DISCOUNT_DATA_RESP);
	ADD_MSG(C2S_SUPER_DISCOUNT_BUY_REWARD_REQ);
	ADD_MSG(S2C_SUPER_DISCOUNT_BUY_REWARD_RESP);
	ADD_MSG(C2S_SUPER_DISCOUNT_ACCUMULATE_REWARD_REQ);
	ADD_MSG(S2C_SUPER_DISCOUNT_ACCUMULATE_REWARD_RESP);

	// 超值折扣(新)
	ADD_MSG(C2S_NEW_SUPER_DISCOUNT_DATA_REQ);
	ADD_MSG(S2C_NEW_SUPER_DISCOUNT_DATA_RESP);
	ADD_MSG(C2S_NEW_SUPER_DISCOUNT_BUY_REWARD_REQ);
	ADD_MSG(S2C_NEW_SUPER_DISCOUNT_BUY_REWARD_RESP);
	ADD_MSG(C2S_NEW_SUPER_DISCOUNT_ACCUMULATE_REWARD_REQ);
	ADD_MSG(S2C_NEW_SUPER_DISCOUNT_ACCUMULATE_REWARD_RESP);

	// 节目活动
	ADD_MSG(C2S_FESTIVAL_ACTIVITY_DATA_REQ);
	ADD_MSG(S2C_FESTIVAL_ACTIVITY_DATA_RESP);
	ADD_MSG(C2S_TAKE_FESTIVAL_ACTIVITY_REWARD_REQ);
	ADD_MSG(S2C_TAKE_FESTIVAL_ACTIVITY_REWARD_RESP);
	ADD_MSG(C2S_FESTIVAL_ACTIVITY_GOODS_EXCHANGE_REQ);
	ADD_MSG(S2C_FESTIVAL_ACTIVITY_GOODS_EXCHANGE_RESP);
	ADD_MSG(C2S_FESTIVAL_ACTIVITY_RED_POINT_REQ);
	ADD_MSG(S2C_FESTIVAL_ACTIVITY_RED_POINT_RESP);

	// 精准推荐
	ADD_MSG(C2S_ACCURATE_RECOMMEND_DATA_REQ);
	ADD_MSG(S2C_ACCURATE_RECOMMEND_DATA_RESP);
	ADD_MSG(C2S_TAKE_ACCURATE_RECOMMEND_GIFT_REQ);
	ADD_MSG(S2C_TAKE_ACCURATE_RECOMMEND_GIFT_RESP);

	// 宝石
	ADD_MSG(C2S_GEM_LIST_REQ);
	ADD_MSG(S2C_GEM_LIST_RESP);
	ADD_MSG(C2S_GEM_COMPOSE_REQ);
	ADD_MSG(S2C_GEM_COMPOSE_RESP);
	ADD_MSG(C2S_GEM_INLAY_REQ);
	ADD_MSG(S2C_GEM_INLAY_RESP);
	ADD_MSG(C2S_GEM_UNLOAD_REQ);
	ADD_MSG(S2C_GEM_UNLOAD_RESP);
	ADD_MSG(C2S_GEM_HOLE_OPEN_REQ);
	ADD_MSG(S2C_GEM_HOLE_OPEN_RESP);
	ADD_MSG(S2C_GEM_DATA_NOTIFY);
	ADD_MSG(C2S_GEM_DECOMPOSE_REQ);
	ADD_MSG(S2C_GEM_DECOMPOSE_RESP);

	// 组队
	ADD_MSG(C2S_TEAM_DUNGEON_ANSWER_QUESTION_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_ANSWER_QUESTION_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_ANSWER_QUESTION_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_DIALOG_OVER_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_DIALOG_OVER_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_DIALOG_OVER_NOITY);
	ADD_MSG(C2S_TEAM_DUNGEON_NEXT_NPC_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_NEXT_NPC_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_NEXT_NPC_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_BOSS_TASK_START_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_BOSS_TASK_START_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_LOTTERY_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_LOTTERY_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_LEAVE_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_LEAVE_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_CREATE_TEAM_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_CREATE_TEAM_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_INVITE_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_INVITE_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_INVITE_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_ACCEPT_INVITE_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_ACCEPT_INVITE_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_ACCEPT_INVITE_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_RECOMMEND_LIST_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_RECOMMEND_LIST_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_MATCH_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_MATCH_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_CANCEL_MATCH_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_CANCEL_MATCH_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_ACCEPT_TASK_REQ);
	ADD_MSG(C2S_TEAM_DUNGEON_TASK_START_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_TASK_START_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_TASK_START_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_RANK_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_RANK_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_BOSS_REWARD_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_DATA_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_DATA_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_SHORTCUT_CHAT_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_SHORTCUT_CHAT_RESP);
	ADD_MSG(C2S_TEAM_DUNGEON_LOTTERY_RECORD_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_LOTTERY_RECORD_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_MATCH_TARGET_NUM_NOTIFY);
	ADD_MSG(C2S_TEAM_DUNGEON_JOIN_IN_REQ);
	ADD_MSG(S2C_TEAM_DUNGEON_JOIN_IN_RESP);
	ADD_MSG(S2C_TEAM_DUNGEON_JOIN_IN_NOTIFY);

	// 登录奖励
	ADD_MSG(C2S_LOGIN_REWARD_DATA_REQ);
	ADD_MSG(S2C_LOGIN_REWARD_DATA_RESP);
	ADD_MSG(C2S_TAKE_LOGIN_REWARD_REQ);
	ADD_MSG(S2C_TAKE_LOGIN_REWARD_RESP);

	// 王者赛
	ADD_MSG(C2S_KING_MATCH_DATA_REQ);
	ADD_MSG(C2S_KING_MATCH_SEARCH_TARGET_REQ);
	ADD_MSG(C2S_TAKE_KING_MATCH_TASK_REWARD_REQ);
	ADD_MSG(C2S_KING_MATCH_SEASON_RANK_REQ);

	// 圣诞节
	ADD_MSG(C2S_CHRISTMAS_DATA_REQ);
	ADD_MSG(S2C_CHRISTMAS_DATA_RESP);
	ADD_MSG(C2S_CHRISTMAS_BATTLE_ENTER_REQ);
	ADD_MSG(S2C_CHRISTMAS_BATTLE_ENTER_RESP);
	ADD_MSG(C2S_CHRISTMAS_BATTLE_LEAVE_REQ);
	ADD_MSG(S2C_CHRISTMAS_BATTLE_LEAVE_RESP);
	ADD_MSG(C2S_CHRISTMAS_ATTACK_BOSS_REQ);
	ADD_MSG(S2C_CHRISTMAS_ATTACK_BOSS_RESP);
	ADD_MSG(C2S_CHRISTMAS_TAKE_BOSS_REWARD_REQ);
	ADD_MSG(S2C_CHRISTMAS_TAKE_BOSS_REWARD_RESP);
	ADD_MSG(S2C_CHRISTMAS_ATTACK_BOSS_NOTIFY);

	// facebook活动
	ADD_MSG(C2S_FACEBOOK_ACTIVITY_DATA_REQ);
	ADD_MSG(S2C_FACEBOOK_ACTIVITY_DATA_RESP);
	ADD_MSG(C2S_TAKE_FACEBOOK_ACCOUNT_BINDING_REWARD_REQ);
	ADD_MSG(S2C_TAKE_FACEBOOK_ACCOUNT_BINDING_REWARD_RESP);
	ADD_MSG(C2S_TAKE_FACEBOOK_SHARE_REWARD_REQ);
	ADD_MSG(S2C_TAKE_FACEBOOK_SHARE_REWARD_RESP);
	ADD_MSG(C2S_FACEBOOK_FRIEND_INVITE_REQ);
	ADD_MSG(S2C_FACEBOOK_FRIEND_INVITE_RESP);
	ADD_MSG(C2S_FACEBOOK_FRIEND_SUMMON_REQ);
	ADD_MSG(S2C_FACEBOOK_FRIEND_SUMMON_RESP);
	ADD_MSG(C2S_TAKE_FACEBOOK_FRIEND_INVITE_REWARD_REQ);
	ADD_MSG(S2C_TAKE_FACEBOOK_FRIEND_INVITE_REWARD_RESP);
	ADD_MSG(C2S_TAKE_FACEBOOK_FRIEND_SUMMON_REWARD_REQ);
	ADD_MSG(S2C_TAKE_FACEBOOK_FRIEND_SUMMON_REWARD_RESP);
	ADD_MSG(C2S_FACEBOOK_FRIEND_INVITE_RECORD_REQ);
	ADD_MSG(S2C_FACEBOOK_FRIEND_INVITE_RECORD_RESP);
	ADD_MSG(C2S_TAKE_FACEBOOK_COMMEND_REWARD_REQ);
	ADD_MSG(S2C_TAKE_FACEBOOK_COMMEND_REWARD_RESP);

	// 在线奖励
	ADD_MSG(C2S_ONLINE_REWARD_DATA_REQ);
	ADD_MSG(S2C_ONLINE_REWARD_DATA_RESP);
	ADD_MSG(C2S_TAKE_ONLINE_REWARD_REQ);
	ADD_MSG(S2C_TAKE_ONLINE_REWARD_RESP);

	// 7天登录
	ADD_MSG(C2S_SEVEN_DAY_LOGIN_DATA_REQ);
	ADD_MSG(S2C_SEVEN_DAY_LOGIN_DATA_RESP);
	ADD_MSG(C2S_TAKE_SEVEN_DAY_LOGIN_REWARD_REQ);
	ADD_MSG(S2C_TAKE_SEVEN_DAY_LOGIN_REWARD_RESP);

	// 充值回馈
	ADD_MSG(C2S_RECHARGE_REWARD_DATA_REQ);
	ADD_MSG(S2C_RECHARGE_REWARD_DATA_RESP);
	ADD_MSG(C2S_TAKE_RECHARGE_REWARD_REQ);
	ADD_MSG(S2C_TAKE_RECHARGE_REWARD_RESP);
	ADD_MSG(C2S_TAKE_RECHARGE_EXTRA_REWARD_REQ);
	ADD_MSG(S2C_TAKE_RECHARGE_EXTRA_REWARD_RESP);

	// 累充奖励
	ADD_MSG(C2S_TOTAL_RECHARGE_REWARD_DATA_REQ);
	ADD_MSG(S2C_TOTAL_RECHARGE_REWARD_DATA_RESP);
	ADD_MSG(C2S_TAKE_TOTAL_RECHARGE_REWARD_REQ);
	ADD_MSG(S2C_TAKE_TOTAL_RECHARGE_REWARD_RESP);

	// 扭蛋抽奖
	ADD_MSG(C2S_ND_LOTTERY_REQ);
	ADD_MSG(S2C_ND_LOTTERY_RESP);
	ADD_MSG(C2S_ND_LOTTERY_RECORD_REQ);
	ADD_MSG(S2C_ND_LOTTERY_RECORD_RESP);

	// 热卖商品
	ADD_MSG(C2S_HOT_SALE_GOODS_DATA_REQ);
	ADD_MSG(C2S_TAKE_HOT_SALE_GOODS_RECHARGE_REWARD_REQ);

	// 转盘
	ADD_MSG(C2S_TURNTABLE_DATA_REQ);
	ADD_MSG(S2C_TURNTABLE_DATA_RESP);
	ADD_MSG(C2S_TURNTABLE_LOTTERY_REQ);
	ADD_MSG(S2C_TURNTABLE_LOTTERY_RESP);

	// 阵营招募
	ADD_MSG(C2S_CAMP_RECRUIT_DATA_REQ);
	ADD_MSG(S2C_CAMP_RECRUIT_DATA_RESP);
	ADD_MSG(C2S_CAMP_RECRUIT_REQ);
	ADD_MSG(S2C_CAMP_RECRUIT_RESP);
	ADD_MSG(C2S_CAMP_RECRUIT_SCORE_TASK_REWARD_REQ);
	ADD_MSG(S2C_CAMP_RECRUIT_SCORE_TASK_REWARD_RESP);
	ADD_MSG(C2S_CAMP_RECRUIT_RECORD_REQ);
	ADD_MSG(S2C_CAMP_RECRUIT_RECORD_RESP);

	// unlock活动
	ADD_MSG(C2S_UNLOCK_ACTIVITY_DATA_REQ);
	ADD_MSG(S2C_UNLOCK_ACTIVITY_DATA_RESP);
	ADD_MSG(C2S_SHOP_SCORE_FINISH_REQ);
	ADD_MSG(S2C_SHOP_SCORE_FINISH_RESP);
	ADD_MSG(C2S_WATCHING_VIDEO_NOTIFY_REQ);
	ADD_MSG(S2C_WATCHING_VIDEO_NOTIFY_RESP);

	// 世界等级任务
	ADD_MSG(C2S_WORLD_LEVEL_TASK_DATA_REQ);
	ADD_MSG(S2C_WORLD_LEVEL_TASK_DATA_RESP);
	ADD_MSG(C2S_TAKE_WORLD_LEVEL_TASK_REWARD_REQ);
	ADD_MSG(S2C_TAKE_WORLD_LEVEL_TASK_REWARD_RESP);
	ADD_MSG(C2S_TAKE_WORLD_LEVEL_TASK_FINAL_REWARD_REQ);
	ADD_MSG(S2C_TAKE_WORLD_LEVEL_TASK_FINAL_REWARD_RESP);

	// 资源战
	ADD_MSG(C2S_PLAYER_RESOURCE_WAR_DATA_REQ);
	ADD_MSG(S2C_PLAYER_RESOURCE_WAR_DATA_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_ENEMY_LIST_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_ENEMY_LIST_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_BATTLE_RECORD_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_BATTLE_RECORD_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_GIVE_UP_OCCUPY_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_GIVE_UP_OCCUPY_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_KEEP_OCCUPY_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_KEEP_OCCUPY_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_CHAPTER_DATA_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_CHAPTER_DATA_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_SAME_RESOURCE_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_SAME_RESOURCE_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_GUILD_RESOURCE_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_GUILD_RESOURCE_RESP);
	ADD_MSG(C2S_RESOURCE_WAR_TECHNOLOGY_UPGRADE_REQ);
	ADD_MSG(S2C_RESOURCE_WAR_TECHNOLOGY_UPGRADE_RESP);

	// 军团战
	ADD_MSG(C2S_GUILD_WAR_ROLE_DATA_REQ);
	ADD_MSG(S2C_GUILD_WAR_ROLE_DATA_RESP);
	ADD_MSG(C2S_GUILD_WAR_OCCUPY_STAR_LIST_REQ);
	ADD_MSG(S2C_GUILD_WAR_OCCUPY_STAR_LIST_RESP);
	ADD_MSG(C2S_GUILD_WAR_DECLARE_WAR_STAR_LIST_REQ);
	ADD_MSG(S2C_GUILD_WAR_DECLARE_WAR_STAR_LIST_RESP);
	ADD_MSG(C2S_GUILD_WAR_STAR_LIST_REQ);
	ADD_MSG(S2C_GUILD_WAR_STAR_LIST_RESP);
	ADD_MSG(C2S_GUILD_WAR_DECLARE_WAR_REQ);
	ADD_MSG(S2C_GUILD_WAR_DECLARE_WAR_RESP);
	ADD_MSG(C2S_GUILD_WAR_ORGANIZE_DEFENSE_REQ);
	ADD_MSG(S2C_GUILD_WAR_ORGANIZE_DEFENSE_RESP);
	ADD_MSG(C2S_GUILD_WAR_EVACUATE_REQ);
	ADD_MSG(S2C_GUILD_WAR_EVACUATE_RESP);
	ADD_MSG(C2S_GUILD_WAR_BUY_HIGH_STAR_BATTLE_TIMES_REQ);
	ADD_MSG(S2C_GUILD_WAR_BUY_HIGH_STAR_BATTLE_TIMES_RESP);
	ADD_MSG(C2S_GUILD_WAR_TAKE_STAR_REWARD_REQ);
	ADD_MSG(S2C_GUILD_WAR_TAKE_STAR_REWARD_RESP);
	ADD_MSG(C2S_GUILD_WAR_STAR_DETAIL_REQ);
	ADD_MSG(S2C_GUILD_WAR_STAR_DETAIL_RESP);
	ADD_MSG(C2S_GUILD_WAR_TOWER_LIST_REQ);
	ADD_MSG(S2C_GUILD_WAR_TOWER_LIST_RESP);
	ADD_MSG(S2C_GUILD_WAR_STAR_UPDATE_NOTIFY);

	// 挂机
	ADD_MSG(C2S_HANG_UP_DROP_DATA_REQ);
	ADD_MSG(S2C_HANG_UP_DROP_DATA_RESP);
	ADD_MSG(C2S_HANG_UP_DROP_REWARD_OBTAIN_REQ);
	ADD_MSG(S2C_HANG_UP_DROP_REWARD_OBTAIN_RESP);


	////////////////////////////////////注册消息////////////////////////////////////////////////
	//其他
	ADD_MSG(C2S_HEART_BEAT_REQ);
	ADD_MSG(S2C_HEART_BEAT_RESP);

	ADD_MSG(C2S_SERVER_TIME_REQ);
	ADD_MSG(S2C_SERVER_TIME_RESP);

	ADD_MSG(C2S_GUIDE_UPDATE_REQ);
	ADD_MSG(S2C_GUIDE_UPDATE_RESP);

	// 	ADD_MSG(C2M_GET_TIME_SYN);
	// 	ADD_MSG(M2C_GET_TIME_CMD);
	// 
	// 	/*--------------------------------------------------------------------------------------------------------------------------*/	
	// 	// 3) GateSvr和MapSvr之间消息注册
	// 	/*--------------------------------------------------------------------------------------------------------------------------*/
	ADD_MSG(G2M_CLIENT_DISCONNECT_CMD);
	ADD_MSG(M2G_CLIENT_KICKOUT_CMD);
	ADD_MSG(M2G_HEART_BEAT);
	ADD_MSG(G2M_HEART_BEAT);
	ADD_MSG(M2G_CLIENT_INFO);


	//  map <-----> open
	ADD_MSG(M2O_SERVERID_CMD);
	ADD_MSG(M2O_HEART_BEAT);
	ADD_MSG(M2O_AUTHENTICATION_CODE_REQ);
	ADD_MSG(M2O_REYUN_STATISTIC_NOTIFY);
	ADD_MSG(M2O_CHECK_USER_INFO_REQ);
	ADD_MSG(M2O_RECHARGE_SEND_GOODS_RESP);
	ADD_MSG(M2O_SDK_ORDER_ID_REQ);
	ADD_MSG(M2O_RECHARGE_SUCCESS_REPORT_NOTIFY);
	ADD_MSG(M2O_STATISTICS_NOTIFY);
	ADD_MSG(M2O_ONLINE_PLAYER_NUM_RESP);
	ADD_MSG(M2O_MYCARD_RECHARGE_SUCCESS_REPORT_NOTIFY);

	ADD_MSG(O2M_HEART_BEAT);
	ADD_MSG(O2M_AUTHENTICATION_CODE_RESP);
	ADD_MSG(O2M_CHECK_USER_INFO_RESP);
	ADD_MSG(O2M_RECHARGE_SEND_GOODS_REQ);
	ADD_MSG(O2M_SDK_ORDER_ID_RESP);
	ADD_MSG(O2M_CP_ORDER_ID_REQ);
	ADD_MSG(O2M_ONLINE_PLAYER_NUM_REQ);
	ADD_MSG(O2M_YGAME_RECHARGE_SEND_GOODS_REQ);
	ADD_MSG(M2O_YGAME_RECHARGE_SEND_GOODS_RESP);
	ADD_MSG(O2M_YGAME_CASHBACK_NOTIFY_REQ);
	ADD_MSG(M2O_YGAME_CASHBACK_NOTIFY_RESP);
	ADD_MSG(O2M_YGAME_BONUS_NOTIFY_REQ);
	ADD_MSG(M2O_YGAME_BONUS_NOTIFY_RESP);
}