// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

#ifndef PROTOBUF_header_2eproto__INCLUDED
#define PROTOBUF_header_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_header_2eproto();
void protobuf_AssignDesc_header_2eproto();
void protobuf_ShutdownFile_header_2eproto();

class Header;

// ===================================================================

class Header : public ::google::protobuf::Message {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  Header* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 roleid = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 1;
  inline ::google::protobuf::uint64 roleid() const;
  inline void set_roleid(::google::protobuf::uint64 value);

  // optional uint32 seq = 2;
  inline bool has_seq() const;
  inline void clear_seq();
  static const int kSeqFieldNumber = 2;
  inline ::google::protobuf::uint32 seq() const;
  inline void set_seq(::google::protobuf::uint32 value);

  // optional string sessionid = 3;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionidFieldNumber = 3;
  inline const ::std::string& sessionid() const;
  inline void set_sessionid(const ::std::string& value);
  inline void set_sessionid(const char* value);
  inline void set_sessionid(const char* value, size_t size);
  inline ::std::string* mutable_sessionid();
  inline ::std::string* release_sessionid();
  inline void set_allocated_sessionid(::std::string* sessionid);

  // optional uint32 re_send_cnt = 4;
  inline bool has_re_send_cnt() const;
  inline void clear_re_send_cnt();
  static const int kReSendCntFieldNumber = 4;
  inline ::google::protobuf::uint32 re_send_cnt() const;
  inline void set_re_send_cnt(::google::protobuf::uint32 value);

  // optional string msg_full_name = 5;
  inline bool has_msg_full_name() const;
  inline void clear_msg_full_name();
  static const int kMsgFullNameFieldNumber = 5;
  inline const ::std::string& msg_full_name() const;
  inline void set_msg_full_name(const ::std::string& value);
  inline void set_msg_full_name(const char* value);
  inline void set_msg_full_name(const char* value, size_t size);
  inline ::std::string* mutable_msg_full_name();
  inline ::std::string* release_msg_full_name();
  inline void set_allocated_msg_full_name(::std::string* msg_full_name);

  // optional uint64 version = 6;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 6;
  inline ::google::protobuf::uint64 version() const;
  inline void set_version(::google::protobuf::uint64 value);

  // optional uint64 uid = 7;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 7;
  inline ::google::protobuf::uint64 uid() const;
  inline void set_uid(::google::protobuf::uint64 value);

  // optional uint32 code = 8;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 8;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:protocol.Header)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_seq();
  inline void clear_has_seq();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  inline void set_has_re_send_cnt();
  inline void clear_has_re_send_cnt();
  inline void set_has_msg_full_name();
  inline void clear_has_msg_full_name();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 roleid_;
  ::std::string* sessionid_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 re_send_cnt_;
  ::std::string* msg_full_name_;
  ::google::protobuf::uint64 version_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_header_2eproto();
  friend void protobuf_AssignDesc_header_2eproto();
  friend void protobuf_ShutdownFile_header_2eproto();

  void InitAsDefaultInstance();
  static Header* default_instance_;
};
// ===================================================================


// ===================================================================

// Header

// optional uint64 roleid = 1;
inline bool Header::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
  clear_has_roleid();
}
inline ::google::protobuf::uint64 Header::roleid() const {
  return roleid_;
}
inline void Header::set_roleid(::google::protobuf::uint64 value) {
  set_has_roleid();
  roleid_ = value;
}

// optional uint32 seq = 2;
inline bool Header::has_seq() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_seq() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_seq() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 Header::seq() const {
  return seq_;
}
inline void Header::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
}

// optional string sessionid = 3;
inline bool Header::has_sessionid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Header::set_has_sessionid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Header::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Header::clear_sessionid() {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    sessionid_->clear();
  }
  clear_has_sessionid();
}
inline const ::std::string& Header::sessionid() const {
  return *sessionid_;
}
inline void Header::set_sessionid(const ::std::string& value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void Header::set_sessionid(const char* value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void Header::set_sessionid(const char* value, size_t size) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Header::mutable_sessionid() {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  return sessionid_;
}
inline ::std::string* Header::release_sessionid() {
  clear_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sessionid_;
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Header::set_allocated_sessionid(::std::string* sessionid) {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    delete sessionid_;
  }
  if (sessionid) {
    set_has_sessionid();
    sessionid_ = sessionid;
  } else {
    clear_has_sessionid();
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional uint32 re_send_cnt = 4;
inline bool Header::has_re_send_cnt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Header::set_has_re_send_cnt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Header::clear_has_re_send_cnt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Header::clear_re_send_cnt() {
  re_send_cnt_ = 0u;
  clear_has_re_send_cnt();
}
inline ::google::protobuf::uint32 Header::re_send_cnt() const {
  return re_send_cnt_;
}
inline void Header::set_re_send_cnt(::google::protobuf::uint32 value) {
  set_has_re_send_cnt();
  re_send_cnt_ = value;
}

// optional string msg_full_name = 5;
inline bool Header::has_msg_full_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Header::set_has_msg_full_name() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Header::clear_has_msg_full_name() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Header::clear_msg_full_name() {
  if (msg_full_name_ != &::google::protobuf::internal::kEmptyString) {
    msg_full_name_->clear();
  }
  clear_has_msg_full_name();
}
inline const ::std::string& Header::msg_full_name() const {
  return *msg_full_name_;
}
inline void Header::set_msg_full_name(const ::std::string& value) {
  set_has_msg_full_name();
  if (msg_full_name_ == &::google::protobuf::internal::kEmptyString) {
    msg_full_name_ = new ::std::string;
  }
  msg_full_name_->assign(value);
}
inline void Header::set_msg_full_name(const char* value) {
  set_has_msg_full_name();
  if (msg_full_name_ == &::google::protobuf::internal::kEmptyString) {
    msg_full_name_ = new ::std::string;
  }
  msg_full_name_->assign(value);
}
inline void Header::set_msg_full_name(const char* value, size_t size) {
  set_has_msg_full_name();
  if (msg_full_name_ == &::google::protobuf::internal::kEmptyString) {
    msg_full_name_ = new ::std::string;
  }
  msg_full_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Header::mutable_msg_full_name() {
  set_has_msg_full_name();
  if (msg_full_name_ == &::google::protobuf::internal::kEmptyString) {
    msg_full_name_ = new ::std::string;
  }
  return msg_full_name_;
}
inline ::std::string* Header::release_msg_full_name() {
  clear_has_msg_full_name();
  if (msg_full_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_full_name_;
    msg_full_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Header::set_allocated_msg_full_name(::std::string* msg_full_name) {
  if (msg_full_name_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_full_name_;
  }
  if (msg_full_name) {
    set_has_msg_full_name();
    msg_full_name_ = msg_full_name;
  } else {
    clear_has_msg_full_name();
    msg_full_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional uint64 version = 6;
inline bool Header::has_version() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Header::set_has_version() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Header::clear_has_version() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Header::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
  clear_has_version();
}
inline ::google::protobuf::uint64 Header::version() const {
  return version_;
}
inline void Header::set_version(::google::protobuf::uint64 value) {
  set_has_version();
  version_ = value;
}

// optional uint64 uid = 7;
inline bool Header::has_uid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Header::set_has_uid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Header::clear_has_uid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Header::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::uint64 Header::uid() const {
  return uid_;
}
inline void Header::set_uid(::google::protobuf::uint64 value) {
  set_has_uid();
  uid_ = value;
}

// optional uint32 code = 8;
inline bool Header::has_code() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Header::set_has_code() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Header::clear_has_code() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Header::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 Header::code() const {
  return code_;
}
inline void Header::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_header_2eproto__INCLUDED
